go.sum
repository_plan9_test.go
worktree_plan9.go

Original created by @fhs at https://github.com/src-d/go-git/pull/1269
```
Not all the tests pass yet but this makes go-git usable on Plan 9.
Please merge this after https://github.com/src-d/go-billy/pull/78.
Fixes #756
Signed-off-by: Fazlul Shahriar <fshahriar@gmail.com>
```

*: add Plan 9 support

---

go.mod
go.sum
plumbing/object/object.go

Original created by @zeripath at https://github.com/src-d/go-git/pull/1291
```
In the British TZ the following time:
1579639200 +0100
will be erroneously parsed as being with the GMT TZ.
This leads to multiple errors with GPG validation.
This PR fixes this by using the provided TZ information to
create a FixedZone and sets that as the TZ
```

plumbing: object, fix date reading

---

options.go
plumbing/object/commit_walker_path.go
repository.go
repository_test.go

Originally created by @ilius at https://github.com/src-d/go-git/pull/1248
```
This allow filtering commits based on directory path, or regexp on file path.
It should be safe to close #562 with this.
LogOptions.FileName and NewCommitFileIterFromIter are kept for compatibility.
Let me know if they should be removed.
```

git.LogOptions: add `PathFilter func(string) bool` 

---

plumbing/object/commit.go

Most commits have relatively small messages, so this was never
noticeable. However, there are some repositories that have
semi-automated messages that can get very large (e.g.
github.com/riscv/riscv-clang and its riscv-trunk branch), on the order
of 109k lines. Changing from string += to using a bytes.Buffer reduces
the time for Commit.Decode for that specific case from 35s to 74ms.
Signed-off-by: David Symonds <dsymonds@golang.org>

plumbing/object: avoid O(N^2) string building when decoding commit message

---

COMPATIBILITY.md

Copied from https://github.com/src-d/go-git/pull/1273
https://github.com/src-d/go-git/issues/847 should likely be re-filed - it would be great if this could be fixed, although I know it's a ton of work.

Update COMPATIBILITY.md to reflect git binary usage for file protocol

---

plumbing/transport/server/receive_pack_test.go
plumbing/transport/server/server.go

When a `Remote` receives a push with only delete commands, it sends a `nil` value for `Packfile` ([related code](https://github.com/go-git/go-git/blob/661b1ace8b4d2a387e2ae130bbb034e62cc8ce11/remote.go#L1064-L1079)), which results in a a `panic: runtime error: invalid memory address or nil pointer dereference` in the code below. This simply fixes that by skipping the processing if its `nil`.
It does seem there is already a test case covering deletes inside the `ReceivePackSuite`, however the [test sends an empty packfile](https://github.com/go-git/go-git/blob/661b1ace8b4d2a387e2ae130bbb034e62cc8ce11/plumbing/transport/test/receive_pack.go#L262) rather than sending `nil`.
If it would be better to update `Remote` to send a similar empty packfile please let me know and I'll be happy to make …

plumbing: transport server check for nil Packfile, fixes ref deletes

---

.github/workflows/git.yml

The variable `GIT_EXEC_PATH` needs to contain an absolute path. This fixes master compatibility test but still fails with `v2.11.0`. I've tested locally and also fails with the same errors. The problem must be somewhere else.

ci: fix compatibility tests for master

---

_examples/config/main.go
config/config.go
config/config_test.go
plumbing/format/config/merged.go
storage/filesystem/config.go
storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/dotgit_test.go

...for reading and writing global (`~/.gitconfig`) and reading system (`/etc/gitconfig`) configs in addition to local repo config.
This is heavily based on / inspired by @djgilcrease's PR on the original src-d repo: https://github.com/src-d/go-git/pull/1243. However, I ran into an issue using that code where if you ran `SetConfig` it would write out the merged system, global, and local config params all to your local `./.git/config` file, which was hard to fix under that architecture.
So, I tried to take a simpler starting approach with this PR but still allow it to accomplish my 2 goals:
1. Show a merged view of system (`/etc/gitconfig`), global (`~/.gitconfig`), and local (`./.git/config`) configs with the same precedence ordering that git itself uses (local overrides global overrides …

plumbing: format, config.Merged to allow access to local and global config

---

README.md

Fix example's link in README.md. It refers to the old project location.

Fix example's link in README.md

---

_examples/config/main.go

It took me a few hours and going through the code of go-git to figure out I need to call `SetConfig` in order for the config changes to be applied to the local config file.
Especially that when doing `CreateRemote` the call to `SetConfig` is actually done behind the scene so the remote appeared in the file. While for the user local settings I had to actually call `SetConfig` myself.
Hope this will save someone a few hours or at least minutes of troubleshooting.

examples: config, Show how to save config changes

---

plumbing/object/change.go
plumbing/object/difftree.go
plumbing/object/rename.go
plumbing/object/rename_test.go
utils/merkletrie/difftree.go

This commit implements the rename detection algorithms used in the
JGit implementation.
Given a list of changes, additions and deletions are extracted and
matched in two ways:
- By exact hash content: all additions and deletions are grouped by
the content hash and paired with the best match based on the file
mode and file path. All the files that cannot be paired are kept
as regular deletions and additions.
- By similar content: a matrix of addition and deletion pairs with
all possible combinations is created and scored by how similar the
content is between both files as well as how similar the file path
is. The pairs with the best score and whose score is equal or
greater than a threshold are paired and turned into a rename.
All the files that cannot be paired are kept as regular …

plumbing: detect renames by hash and similar content in diff tree

---

storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/dotgit_test.go

Described in finer detail in the commit messages, readReferenceFile() where the path resolves to a directory succeeds on FreeBSD. The root of the problem is that on the other platforms go-git operates on, read() on a dir fd will fail and thus readReferenceFile() will fail.
This small series amends an existing test to demonstrate the problem (the assert at dotgit_test.go:121 will fail the test on FreeBSD), then fixes it by sanity-checking with Stat() that we're not looking at a directory. The second commit fixes up the test to ensure that readReferenceFile() is returning the specific error we're adding, rather than just any error.
This was noticed when Gitea on FreeBSD would 500 while attempting to read a branch with a `/` in any part of the name, as it would split and readReferenceFile() …

storage/filesystem: dotgit, sanity check provided reference path 

---

internal/color/color.go
plumbing/format/diff/colorconfig.go
plumbing/format/diff/unified_encoder.go
plumbing/format/diff/unified_encoder_test.go

Fixes #33.
This is a draft PR. Please tell me if it more-or-less follows the project's coding style and what changes are likely to be needed to make it more acceptable.
At the moment, it only supports the default git diff colors as defined by git 2.26.2. It should be extensible to reading custom colors from a git config file, if needed.
Before merging, this needs a few tweaks to ensure the output matches git's as far as reasonably possible.

Add initial colored diff support

---

plumbing/object/commit.go
plumbing/object/tree.go
plumbing/object/tree_test.go

This makes the renames detect general available in the `Commit` and `Tree` objects. Making the old behavior optimal. This is a change of behavior than maybe consider breaking changes, but it's an improvement over the previous diff and aligns it with the expected behavior of the function. If still some need access to the old logic can be used.

plumbing: object, make renames diff default

---

plumbing/format/diff/unified_encoder.go

This is a work-in-progress PR on top of #46 to update the `plumbing/diff` package. It is not ready to be considered for merge yet.
Goals:
* There should be no changes to the API, this is an internal clean-up.
* Port the code to use `strings.Builder` more and `fmt.Fprintf`/`bytes.Buffer` less, which should improve both readability and performance. Note that `strings.Builder` did not exist when the code was originally written.
* Fix some minor issues around colored diffs (notably that color resets should occur before newlines if possible, not after).

plumbing: diff, refresh internals

---

plumbing/object/rename.go
plumbing/object/rename_test.go

This fixes an issue where exact renames detection could leave gaps
with nil changes in the added and deleted change slices. That could
lead to panics in the content rename detection and others if the
user had set OnlyExact to true.

plumbing: exact renames detection could leave gaps in the changes

---

plumbing/object/rename.go

The int wasn't converted into an unsigned int, in the rename.go file, which caused an error while building

plumbing: object, Fixed the ambiguous implicit conversions causing errors while building . 

---

config/refspec.go
config/refspec_test.go
plumbing/hash.go
plumbing/hash_test.go
remote.go
remote_test.go

This implements the support of refspec with exact SHA1 in `Remote.Fetch`.
This may be only used on sever with the `AllowReachableSHA1InWant` or `AllowTipSHA1InWant`, otherwise `Remote.Fetch` returns `ErrExactSHA1NotSupported`. (GitHub supports it)
Closes https://github.com/go-git/go-git/issues/56

Remote.Fetch: support exact SHA1 refspecs

---

plumbing/format/diff/unified_encoder.go
plumbing/format/diff/unified_encoder_test.go

This PR modifies the colored diff output to reset the color at the end of the line, rather than at the start of the next line. The visual results are unchanged, but it makes diffs easier to compare as you no longer get color resets at the end of the diff with no trailing newline.

plumbing: diff, reset color at end of line

---

options.go
remote.go
remote_test.go

This implements the support of force in Remote.Push.
When Force option is true, `git push` becomes `git push --force`.
Ref.
> All of the rules described above about what’s not allowed as an update can be overridden by adding an the optional leading + to a refspec (or using --force command line option).
https://git-scm.com/docs/git-push

Remote.Push: support force option

---

plumbing/format/packfile/diff_delta.go
plumbing/format/packfile/encoder.go
plumbing/format/packfile/encoder_test.go
plumbing/format/packfile/packfile.go
plumbing/format/packfile/parser.go
plumbing/format/packfile/patch_delta.go
storage/filesystem/object.go
storage/test/storage_suite.go

`Close()` method of `EncodedObject.Reader()` and `EncodedObject.Writer()` weren't called in some code paths, causing fd leak.
This commit closes all readers and writers used within this repo, along with `ioutil.CheckClose()`.

Close Reader & Writer of EncodedObject after use

---

_examples/README.md
_examples/tag-create-push/main.go

Trying to reduce the cost of adopting the library for jobs happening on ci/cd systems. This is the one of the things we are doing before releasing into prod, set a common git tag for all our repos. It took me a couple of hours to make this example working, so hopefully it will save some time for others.

examples: tag, Add create and push new tag

---

go.mod
go.sum
options.go
repository.go
storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/repository_filesystem.go
storage/filesystem/dotgit/repository_filesystem_test.go
worktree_test.go

Adopted already existing older patch: https://github.com/src-d/go-git/pull/1098 — but with changes:
- Has submodules support:
- use WORKTREE_GIT_DIR/modules instead of COMMON_GIT_DIR/modules (!);
- use COMMON_GIT_DIR/objects;
- use COMMON_GIT_DIR/config.
- More straithforward naming: explicitly use commonfs or fs in DotGit.
Possibly there can be more cases to catch. But our testing shows it works ok.
We use go-git library in [werf gitops tool](https://github.com/werf/werf) and your library is awesome. Hope it will receive future support!

storage: filesystem, support .git/commondir repository layout

---

worktree.go
worktree_test.go

If you run 'git pull', do a commit and run 'git pull' again git will
report "Already up to date" whereas go-git would report a reports
non-fast-forward update. This commit changes the behavior of go-git to
match that of git.

Worktre: Pull, report "Already up to date" when local repository ahead of remote

---

plumbing/format/gitignore/dir.go
plumbing/format/gitignore/dir_test.go

This PR
* Uses bufio.Scanner to read LF and CRLF interchangeable
Resolves #114 
Implements a different approach to #107

plumbing: format, .gitignore crlf fix

---

internal/revision/parser.go
internal/revision/parser_test.go
repository.go
repository_test.go
storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/dotgit_test.go
storage/filesystem/object.go
storage/filesystem/object_test.go

Like `git rev-parse <prefix>`, this enumerates the hashes of objects
with the given prefix and adds them to the list of candidates for
resolution.
This has an exhaustive slow path, which requires enumerating all objects
and filtering each one, but also a couple of fast paths for common
cases. There's room for future work to make this faster; TODOs have been
left for that.
Fixes #135.

Repository.ResolveRevision, support partial hashes

---

worktree_commit.go

Hello.
Partially fixes #113
Speeding up `worktree.Commit("message", &CommitOptions{All: true})` due to invoking `worktree.doAddFile(..)` directly and avoid invoking `worktree.Status()` every time.
In my case it speeds up commit from 70 sec to 2-5 seconds

Worktree.Commit: speed up commit with all: true option

---

remote.go
remote_test.go

This fixes a bug where attempting to delete a ref with `Force: true` in the `PushOptions` will not do anything.
This is because the `Force` push option prepends `+` to every refspec that doesn't already have it. This results in a refspec like `:refs/heads/branch` being turned in to `+:refs/heads/branch` which is not valid, so the ref does not get deleted.
To fix this, I've amended the check for whether to prepend `+` to a refspec to also make sure the refspec is not for a delete.

git: remote, Fix deleting references when force pushing.

---

plumbing/format/config/common.go
plumbing/format/config/common_test.go
plumbing/format/config/option.go
plumbing/format/config/option_test.go
plumbing/format/config/section.go
plumbing/format/config/section_test.go

This PR complete the Config functions.
Add Options.Has to check if an Option exist.
Wherever a collection of Option exist, make sure that the following functions exists as well:
- Option
- OptionAll (new, return all values)
- HasOption (new)
- AddOption
- SetOption
- RemoveOption
For Config and Section, make sure that the following exist to access the sublevel:
- X
- HasX (HasSection was missing)
- RemoveX (RemoveSubsection was missing)
This PR also does some shuffling to have a consistent ordering of functions.

config: add missing functions for completeness

---

remote.go
remote_test.go

Small quality of life improvement - if Fetch can return a distinct error type
as opposed to fmt.Errorf("couldn't find remote ref") then it becomes very easy
for callers to determine what kind of failure occurred using the new-ish
errors.Is and errors.As api.
ref https://golang.org/pkg/errors/

Remote.Fetch: return a unique error type when ref not found

---

worktree.go
worktree_test.go

Original issue created by @tyru at https://github.com/src-d/go-git/issues/737
This PR supports relative URLs in `.gitmodules` which refers to the superproject's remote origin.

git: worktree, Support relative submodule URL.

---

submodule.go
worktree.go
worktree_test.go

With the current behavior, the config will always hold the resolved,
absolute URL, leavin the user of go-git no choice to determine whether
the original URL is relative or not.
This changes to employ relative URL resolution only when resolving
a submodule to a repository to keep the correct configuration
'unresolved' and intact.
Change relative resolution using `filepath.Dir` to `path.Join` while
parsing both the 'root' and the relative URL with `net/url.URL`.
Adapt test to verify the new behavior.
Re-fixes #184 (see comments).

Fix relative submodule resolution

---

config/config.go
config/config_test.go

Adds a new struct to the Config struct that includes the `init.defaultBranch` variable as mentioned [here](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-config.html#FILES)
>init.defaultBranch
>    Allows overriding the default branch name e.g. when initializing a new repository or when cloning an empty repository.
>

config: add init.defaultBranch to the config

---

plumbing/protocol/packp/capability/capability.go

Adding the following capabilities, which seem to be part of the upload-pack in [latest git version](https://git-scm.com/docs/protocol-capabilities/):
- object-list
- filter

Adding "object-format" and "filter" capabilities

---

options.go
plumbing/transport/client/client.go
plumbing/transport/common.go
remote.go
repository.go
worktree.go

This PR add insecureSkipTLSVerify and cabundle to any remote http calls
so that https repo with private CA signed can be used. This is the
equivalent of https.sslVerify and GIT_SSL_CAINFO

Add insecureSkipTLS and cabundle

---

worktree.go
worktree_test.go

When using a separate worktree directory while working on a bare repository, cleaning with `CleanOptions{Dir: true}` would also remove the root worktree directory if empty.

worktree: Don't remove root directory when cleaning

---

worktree_commit.go
worktree_commit_test.go

Hi! 
If I do a simple single file commit using go-git, lots of files within .git/objects/ are touched - they all has the same last modified timestamp. If I do that same simple commit using the regular git CLI, only few files are touched. 
The change of this PR seems to fix this behavior by simply checking if the object is already stored. But maybe I'm missing something?
However, the current gain in performance is impressive: on my test repository (25k files, 1k commits, total size <100MB) the time to commit drops from 3.4s down to 2.2s.

git: worktree_commit, just store objects not already stored

---

plumbing/format/gitignore/dir.go

This patch fixes an inconsistent gitconfig location documented in the `plumbing/format/gitignore` package.

plumbing: gitignore, Fix gitconfig path in LoadSystemPatterns doc

---

plumbing/format/diff/unified_encoder.go
plumbing/format/diff/unified_encoder_test.go

The default behavior here remains the same, but this change does
allow consumers of the UnifiedEncoder to set their own path prefixes
which will override the defaults of a/ and b/.
Setting this should be analogous to setting `--src-prefix` and
`--dst-prefix` in `git diff`.
See https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---src-prefixltprefixgt

diff: Allow srcPrefix and dstPrefix to be configured

---

options.go
remote.go
remote_test.go

The git protocol itself uses a compare-and-swap mechanism, where changes
send the old and new values and the change is only applied if the old
value matches. This is used to implement the --force-with-lease feature
in git push.
go-git populates the `old` field with the current value of the ref that
is read from the remote. We can implement a convenient (albeit more
limited) form of the --force-with-lease feature just by allowing the
caller to specify particular values for this ref.
Callers can then implement complex multi-step atomic operations by
reading the ref themselves at the start of the process, and passing to
in RequireRemoteRefs at the end. This is also a suitable building block
for implementing --force-with-lease (#101), which is mostly an exercise
in computing the correct hash …

Remote: add RequireRemoteRefs to PushOptions

---

plumbing/transport/ssh/common.go
plumbing/transport/ssh/common_test.go
worktree_commit_test.go

Ignore the error on close when the connection is already closed
Fixes #70

transport: ssh, fix cloning large repositories

---

plumbing/transport/common.go
plumbing/transport/http/common.go
plumbing/transport/http/receive_pack.go
plumbing/transport/http/upload_pack.go
plumbing/transport/http/upload_pack_test.go
plumbing/transport/internal/common/common.go
plumbing/transport/server/server.go
remote.go
remote_test.go
repository_test.go

This is primarily for the sake of the http transport, which otherwise makes its first call without a context, causing context timeouts to not work if the remote is unresponsive.
Fixed up several tests which were getting this wrong. I am particularly fond of the ones which canceled the context and then proceeded to test that the function worked after being canceled.
The AdvertisedReferences function can be removed after this change, but this is technically breaking the API, since library users could call it, so it should really be deferred to v6.

plumbing: wire up contexts for Transport.AdvertisedReferences

---

go.mod
go.sum
options.go
plumbing/object/commit.go
plumbing/object/commit_test.go
plumbing/object/tag.go
plumbing/object/tag_test.go
repository.go
repository_test.go
worktree_commit.go
worktree_commit_test.go

Replace golang.org/x/crypto/openpgp by github.com/ProtonMail/go-crypto/openpgp

---

submodule.go

Sometimes submodules are not updated for long periods of time and the tree that holds the commit they point to gets removed at some point, which results in commits that are orphaned, but still reachable using [`allow-reachable-sha1-in-want`](https://git-scm.com/docs/protocol-capabilities#_allow_reachable_sha1_in_want) Git's wire protocol capability.
Here's a real case: https://github.com/cirruslabs/cirrus-ci-docs/pull/830#issuecomment-812618218.
This change makes sure go-git will behave similarly to Git in such cases, which [does a subsequent fetch](https://github.com/git/git/blob/080627942802e767b068a491f3d349227f4e2cdc/submodule.c#L1571-L1577) using a commit hash.

Fetch submodules pointing to orphaned but still reachable commits

---

common.go

This is never used in the code, and not available publicly, so safe to remove.

*: remove unused unexported const

---

plumbing/transport/ssh/auth_method.go
plumbing/transport/ssh/auth_method_test.go

plumbing: transport/ssh, support more formats in `NewPublicKeys` SSH helper

---

remote.go
remote_test.go

It's from this discussion: https://github.com/go-git/go-git/pull/246#discussion_r592130087
When a user calls `go-git` package to do `git ls-remote` check, we should provide a timeout. Otherwise, this will be stuck in some situation, and cause a controller which is using `List` alway waits again and again.. This is not expected I think.
This pull request add a `ListContext` for `List` func and pass `context`. For context, I set `10s` timeout. If exceed 10s, then `List` func will exit. Maybe `10s` is too short, we can discuss a reasonable value about it.
Also I add a unit test to test timeout case. Locally, all unit tests passed.

Remote: new ListContext function

---

plumbing/transport/internal/common/common.go
remote.go
remote_test.go

We'd previously get an error "object not found" when attempting to fetch a new depth on a shallow clone. This PR fixes the issue and adds a relevant test.
We could not get untouched tests to fully pass in our environment, with or without our changes. We're hoping your CI is properly configured to run the entire suite, if not we can investigate further.
Let me know if there are any changes you'd like to see before accepting this PR.
Thanks!

git: Add support for deepening shallow clones

---

plumbing/object/patch.go

`int(math.Floor(deln / scaleFactor)) ` return negative value cause strings.Repeat panic
```
strings.Repeat(0x2322604, 0x1, 0xfffffffffffffff1, 0x0, 0x0)
/usr/local/go/src/strings/strings.go:529 +0x5e5
github.com/go-git/go-git/v5/plumbing/object.printStat(0xc0003d0000, 0x1, 0x1, 0xc0003d0000, 0x1)
/go/pkg/mod/github.com/go-git/go-git/v5@v5.3.0/plumbing/object/patch.go:291 +0x225
github.com/go-git/go-git/v5/plumbing/object.FileStats.String(...)
/go/pkg/mod/github.com/go-git/go-git/v5@v5.3.0/plumbing/object/patch.go:238
dory.gitGetDiff(0xc00100b0b0, 0xc000c58780, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0)
/root/devops-dory-engine/Codes/Backend/dory-engine/dory/git.go:134 +0x7bd
```

plumbing: object/patch, printStat strings.Repeat cause panic

---

remote.go

It looks like a test value was shipped breaking a lot of the usage of the library.
Resulting very quickly in:
```
Error: context deadline exceeded
```
Apologies if this does not come in the right format, happy to provide more

remote: patch default timeout for `List` from 600ms to 10s

---

plumbing/format/packfile/delta_test.go
plumbing/format/packfile/encoder_advanced_test.go
plumbing/format/packfile/encoder_test.go
plumbing/format/packfile/fsobject.go
plumbing/format/packfile/packfile.go
plumbing/format/packfile/packfile_test.go
plumbing/format/packfile/patch_delta.go
plumbing/format/packfile/scanner.go
storage/filesystem/dotgit/reader.go
storage/filesystem/object.go
storage/filesystem/object_test.go
storage/filesystem/storage.go
utils/ioutil/common.go

This PR adds code to prevent large objects from being read into memory
from packfiles or the filesystem through the use of a new `Option`, the `LargeObjectThreshold`.
Objects greater than the provided (optional) `LargeObjectThreshold` are now no longer directly stored in the cache
or read completely into memory.
This PR differs and improves the previous broken #303 by fixing several
bugs in the reader and transparently wrapping ReaderAt as a Reader.
Signed-off-by: Andrew Thornton <art27@cantab.net>
---
(UPDATED: Make LOT an Option on the ObjectStorage - defaulted to off.)

plumbing: format/packfile, prevent large objects from being read into memory completely

---

_examples/README.md
_examples/find-if-any-tag-point-head/main.go

I was trying to find if there was a tag referencing HEAD, it took me a while playing with examples which were key to be successful, so I've decided to add this example in case this is useful for someone else in the future.
Cheers.

examples: added "tag find if head is tagged"

---

plumbing/format/gitignore/dir.go
plumbing/format/gitignore/dir_test.go

Read the `.git/info/exclude` file too, as per the official Git implementation.
> Patterns which are specific to a particular repository but which do not need to be shared with other related repositories (e.g., auxiliary files that live inside the repository but are specific to one user’s workflow) should go into the `$GIT_DIR/info/exclude` file.
References:
- https://git-scm.com/docs/gitignore
- https://github.com/git/git/blob/eb27b338a3e71c7c4079fbac8aeae3f8fbb5c687/Documentation/gitignore.txt

plumbing: gitignore, Read .git/info/exclude file too.

---

options.go
remote.go
remote_test.go

Using plain git, the command `git push ${sha}:refs/heads/some-branch`
actually ensures that the remote branch `some-branch` points to the
commit `${sha}`.
In the current version of go-git, this results in an "everything is
up to date" error.
When a source reference is not found, check the object storage to find
the sha. If it is found, consider pushing this exact commit.
fixes: #105

Remote: Push, add support to push commits per hashes

---

options.go
plumbing/protocol/packp/updreq.go
plumbing/protocol/packp/updreq_encode.go
plumbing/protocol/packp/updreq_encode_test.go
remote.go

Add possibility to send push-options to the server. This is the equivalent to `git push --push-option=SomeKey=SomeValue -o AnotherKey=AnotherOption`.
Fixes #268.

Remote: PushOptions add push-options

---

plumbing/format/index/encoder.go
plumbing/format/index/encoder_test.go

Currently the index encoder does not support the v3 index format. This
change adds support to the encoder.

plumbing: format, support v3 index

---

_examples/remotes/main.go

examples: remote fix typo

---

storage/filesystem/dotgit/dotgit_test.go
storage/filesystem/object_test.go

The `os.SEEK_*` constants have been deprecated since Go 1.7.
It is now recommended to use the equivalent `io.Seek*` constants.
Switch `os.SEEK_CUR` to `io.SeekCurrent`,
and `os.SEEK_SET` to `io.SeekStart`.

storage: filesystem, switch from os.SEEK_* to io.Seek*

---

plumbing/protocol/packp/updreq.go

Per the [Go Spec](https://go.dev/ref/spec#Constant_declarations),
the following yields the type `Action` for `Bar` and `Baz`
only if there is no `=`.
const (
Foo Action = ...
Bar
Baz
)
The following has the type `Action` for the first item,
but not the rest. Those are untyped constants
of the corresponding type.
const (
Foo Action = ...
Bar        = ...
Baz        = ...
)
This means that `packp.{Update, Delete, Invalid}` are currently
untyped string constants, and not `Action` constants
as was intended here.
This change fixes these.

packp: Actions should have type Action

---

options.go
remote.go
remote_test.go

--force-with-lease allows a push to force push with some safety
measures. If the ref on the remote is what we expect, then the force
push is allowed to happen.
See https://git-scm.com/docs/git-push#Documentation/git-push.txt---force-with-leaseltrefnamegt
for more information

Remote: Push, add ForceWithLease Push Option

---

config/branch.go
config/config.go
config/config_test.go

Since release 1.7.9 git supports branch description config field https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.9.txt
Edit branch description:`git branch --edit-description`
Show branch description:  git config branch.$BRANCH.description
My PR introduces support for this feature. It uses some hacks to overcome an inconsistency with reference git implementation in config encoder, which I want to fix in an other PR (since it may require a lot of fixes in golden tests)

config: add branch description support

---

options.go
plumbing/format/index/index.go
plumbing/object/treenoder.go
repository_test.go
utils/merkletrie/difftree.go
utils/merkletrie/filesystem/node.go
utils/merkletrie/index/node.go
utils/merkletrie/internal/fsnoder/dir.go
utils/merkletrie/internal/fsnoder/file.go
utils/merkletrie/noder/noder.go
utils/merkletrie/noder/noder_test.go
utils/merkletrie/noder/path.go
worktree.go
worktree_test.go

This is the initial logic to support a simple sparse checkout where
directories to be included can be specified in CheckoutOptions.
This change doesn't fully support the sparse patterns, nor does it
include optimizations in the index to collapse flie entries that are not
included into its parent directory.

Worktree: Checkout, simplified sparse checkout

---

options.go
plumbing/protocol/packp/updreq_encode_test.go
remote.go

push --atomic allows a push to succeed or fail atomically. If one ref
fails, the whole push fails. This commit allows the user to set Atomic
as an option for a push.

Remote: Push, add atomic to push options

---

common_test.go
config/config_test.go
plumbing/format/packfile/fsobject.go
plumbing/format/packfile/packfile_test.go
plumbing/format/packfile/parser.go
plumbing/object/patch.go
plumbing/protocol/packp/common.go
plumbing/protocol/packp/updreq_encode.go
plumbing/protocol/packp/uppackresp.go
plumbing/revlist/revlist_test.go
plumbing/transport/client/client_test.go
plumbing/transport/internal/common/common.go
plumbing/transport/ssh/common_test.go
remote.go
remote_test.go
storage/filesystem/dotgit/dotgit_test.go
storage/filesystem/object_test.go
storage/transactional/config_test.go
storage/transactional/reference.go
utils/merkletrie/noder/noder_test.go
worktree_commit_test.go
worktree_test.go

[staticcheck] reported a number of unused fields, functions, types, and
variables across the code.
[staticcheck]: https://staticcheck.io/
Use them where possible (assert unchecked errors in tests, for example)
and remove them otherwise.
There were a few special cases that are on their own commits to
cherry-pick separate from the unused deletions.
- storage/transactional: The assertion appears to be intended to validate
the unused `cfg` variable, not `temporalCfg` which was validated earlier.
- transactional/ReferenceStorage: `packRefs` is intended to be assigned to
from the `PackRefs()` method but never read. Further, because the assignment
happens inside a value receiver, not a pointer receiver, the value is never
actually recorded (so it's a no-op).
- remote/addReachableTags: Membership …

Remove unused vars/types/funcs/fields

---

config/config.go
object_walker.go
plumbing/format/commitgraph/file.go
plumbing/format/gitattributes/attributes.go
plumbing/format/idxfile/decoder.go
plumbing/object/change_adaptor.go
prune.go
remote.go
repository.go
repository_test.go
storage/filesystem/dotgit/reader.go
storage/memory/storage.go

Per [Go Code Review Comments][1],
> Error strings should not be capitalized (unless beginning with proper
> nouns or acronyms) or end with punctuation
staticcheck's [ST1005][2] also complains about these. For example,
```
object_walker.go:63:10: error strings should not be capitalized (ST1005)
object_walker.go:101:10: error strings should not be capitalized (ST1005)
object_walker.go:101:10: error strings should not end with punctuation or a newline (ST1005)
plumbing/format/commitgraph/file.go:17:26: error strings should not be capitalized (ST1005)
```
This fixes all instances of this issue reported by staticcheck.
[1]: https://github.com/golang/go/wiki/CodeReviewComments#error-strings
[2]: https://staticcheck.io/docs/checks/#ST1005
---
Feel free to reject if you don't want the error …

error strings: Don't capitalize, use periods, or newlines

---

plumbing/protocol/packp/capability/capability.go
plumbing/protocol/packp/ulreq_test.go
plumbing/protocol/packp/updreq_test.go
plumbing/protocol/packp/uppackreq_test.go

was still using go-git 4.x as agent.

plumbing: protocol/pakp, update agent

---

repository.go
repository_test.go

When fs.Stat returns an error, pathinfo may be nil. In such situations
the only safe response seems to be to return the error to the caller.
Without this fix, accessing pathinfo.IsDir() below would lead to a crash
dereferencing a nil pointer.
This crash can be reproduced by trying to initialize a Git repo with an
invalid path name.
Also see: https://github.com/muesli/gitty/issues/36

Repository: don't crash accessing invalid pathinfo

---

internal/revision/parser.go
internal/revision/parser_test.go

Hello there!
This PR fixes a bug in the revision parser which would cause an endless loop when parsing revisions containing opening braces `{` but no closing braces `}`.
The bug is fixed by adding a check that breaks the `for` loop if the token ends up as `eof` in situations where the loop is looking for the closing brace.
The bug was found with the help of [go-fuzz](https://github.com/dvyukov/go-fuzz). Let me know if you're interested in the fuzz test setup in case you want to exercise the parsing some more!

revision: fix endless looping in revision parser

---

worktree_bsd.go
worktree_linux.go
worktree_unix_other.go

Use the syscall method instead of repeating the type conversions for
the syscall.Stat_t Atim/Atimespec/Ctim members.

Worktree: use syscall.Timespec.Unix

---

plumbing/protocol/packp/capability/list.go
plumbing/protocol/packp/capability/list_test.go

Previously, calling `Set($CAPABILITY, ...)` on a `capability.List` where `$CAPABILITY`
was already present would correctly replace the existing value of that capability, but
would also result in that capability being listed twice in the internal `l.sort` slice.
This manifested publicly when the `List` was encoded as the same capability appearing
twice with the same value in the encoded output.
A new test case is added. Prior to the fix, the new test case failed like this:
```
$ go test -v
=== RUN   Test
----------------------------------------------------------------------
FAIL: list_test.go:125: SuiteCapabilities.TestSetDuplicate
list_test.go:133:
c.Assert(cap.String(), check.Equals, "agent=bar")
... obtained string = "agent=bar agent=bar"
... expected string = "agent=bar"
OOPS: 23 …
```

plumbing: packp, Avoid duplicate encoding when overriding a Capability value.

---

plumbing/protocol/packp/capability/capability.go
plumbing/protocol/packp/capability/capability_test.go
plumbing/protocol/packp/ulreq.go
plumbing/protocol/packp/updreq.go
plumbing/transport/server/server.go

The `git` command allows users to specify custom content using the `GIT_USER_AGENT` environment variable. This is helpful when understanding demand and performance in large, complex environments. go-git currently has a static configuration specifying the library and version (i.e., `go-git/5.x`).  These changes allow go-git library users to specify  additional content in their user agent by specifying `GO_GIT_USER_AGENT_EXTRA` in their system's environment.

plumbing: packp and server, Include the contents of `GO_GIT_USER_AGENT_EXTRA` as the git user agent. Fixes #529

---

plumbing/format/objfile/writer.go
plumbing/format/packfile/parser_test.go
plumbing/format/packfile/patch_delta.go
plumbing/format/packfile/scanner.go
plumbing/reference.go
plumbing/reference_test.go
storage/filesystem/object.go
worktree.go

[Recently we worked](https://github.com/fluxcd/go-git/pull/5) on some optimisations that could benefit upstream.
The changes improved benchmarks results across number of executions (`+60%`), time (`-4300000 ns/op`), memory (`-23200000 B/op`) and allocations (`-800 allocs/op`).
```
name       old time/op    new time/op    delta
Parser-16    11.9ms ± 1%     7.4ms ± 1%  -37.77%  (p=0.008 n=5+5)
name       old alloc/op   new alloc/op   delta
Parser-16    30.7MB ± 0%     4.8MB ± 2%  -84.42%  (p=0.008 n=5+5)
name       old allocs/op  new allocs/op  delta
Parser-16     4.19k ± 0%     3.48k ± 0%  -16.84%  (p=0.008 n=5+5)
```
Comparing the memory profile of both executions, shows that the gains are primarily in the zlib writing code.
For bench mark delta on the ReferenceName optimisations:
``` …
```

Parse optimisations

---

plumbing/format/gitattributes/pattern.go
plumbing/format/gitattributes/pattern_test.go

When a path is deeper than the single asterisk pattern the code would
crash with a "index out of range".
This change checks the length of the remaining pattern before it
references an element of that slice.
With a single trailing asterisk paths deeper than the pattern should not
get the attributes.
For example with the following `.gitattributes` file:
thirdparty/* linguist-vendored
This is how git handles it:
$ git check-attr --all thirdparty/README.md
thirdparty/README.md: diff: markdown
thirdparty/README.md: linguist-vendored: set
$ git check-attr --all thirdparty/package/README.md
thirdparty/package/README.md: diff: markdown

plumbing: gitattributes, Avoid index out of range 

---

_examples/azure_devops/main.go
plumbing/protocol/packp/srvresp.go
plumbing/protocol/packp/srvresp_test.go
plumbing/protocol/packp/uppackresp.go
plumbing/protocol/packp/uppackresp_test.go

Azure DevOps requires capabilities `multi_ack` / `multi_ack_detailed`, which are not fully implemented and by default are included in `transport.UnsupportedCapabilities`.
The initial clone operations require a full download of the repository, and therefore those unsupported capabilities are not as crucial, so by removing them from that list allows for the first clone to work successfully.
Additional fetches will yield issues, therefore to support that repository users have to work from a clean clone until those capabilities are fully supported. Commits and pushes back into the repository have also been tested and work fine.
This PR adds an example for cloning Azure DevOps repositories.

Allow unsupported `multi_ack` capability

---

plumbing/format/config/encoder.go
plumbing/format/config/fixtures_test.go

This is a fix for https://github.com/go-git/go-git/issues/309 'Can't clone branch ref name with hash/number sign (#)'
The problem is occurring because the # character in a git config file is interpreted as a comment. In fact, the config-file writer needs to escape a number of characters that would cause it to create an invalid config-file.
Following example copied from #611
When a repository is cloned a config file is created in the .git directory. I have mocked up an example below by hand:
```ini
[core]
bare = false # This is just a comment so is ignored
[remote "origin"]
url = https://https://github.com/myrepo.git
fetch = +refs/heads/release/mybranchname:refs/remotes/origin/release/mybranchname
```
However, if there is a # character in the branch name like this:
```ini
[core]
bare = …
```

plumbing: config, Branch name with hash can be cloned. Fixes #309

---

plumbing/object/rename.go

The size of the similarity matrix is not limited and can be quite big
when lots of files are deleted and added in a commit.
Signed-off-by: Javi Fontan <jfontan@gmail.com>

plumbing: object, rename calculation uses too much memory

---

options.go
worktree_commit.go
worktree_commit_test.go
worktree_test.go

BuildTree now returns an `ErrEmptyCommit` error, when there are no changes to be committed, which can be opted-out via `CommitOptions.AllowEmptyCommits`.
This is a breaking change which enables applications to detect when empty commits are to be created.
Some instances in which this can occur is when the fs (e.g. `billy/osfs`) make changes to the underlying files, causing a conflict between what the previous Git worktree state was, and the current state. Changes to the fs implementations are orthogonal to this, and will be dealt with separately.
The new behaviour aligns with the Git CLI, in which empty commits returns the error message: `nothing to commit, working tree clean`.

CommitOptions: AllowEmptyCommits, return error instead of creating empty commits

---

worktree_status.go
worktree_test.go

This PR is for fixing https://github.com/go-git/go-git/issues/223. There is a PR https://github.com/go-git/go-git/pull/242 for the same purpose but it has not been updated after a maintainer's review so I made a new PR.

Worktree: Add, fix add removed files. Fixes #223

---

worktree.go
worktree_test.go

When we delete dir1/dir2/file1, we currently check if dir2 becomes empty with the deletion of file1, and if so, we delete dir2.  If dir1 becomes empty with the deletion of dir2, we don't notice that, and dir1 is left behind.
This commit adds a loop to check each parent directory in the file path for emptiness, removing empty directories along the way until a non-empty directory is found (or an error occurs).

Worktree, check for empty parent dirs during Reset (Fixes #670)

---

plumbing/object/signature.go
plumbing/object/signature_test.go
plumbing/object/tag.go
plumbing/object/tag_test.go

This PR enables support for extracting the SSH and X509 signatures from (annotated) Git tags, as an initial step to support the verification of more signatures than just PGP in go-git.
The ported logic from Git further ensures that we look for a signature at the tail of an annotation, instead of the first signature we find in the annotation, as this could theoretically result in a faulty signature getting detected if part of a an annotation itself (e.g. by being placed in the middle as part of an inherited message).
For commits, no further change is required as the current extraction of any signature (format) from `gpgsig` in the commit header is sufficient for manual verification.
In a future iteration, we could add `signature/ssh` and `signature/x509` packages to further enable people …

plumbing: support SSH/X509 signed tags

---

_examples/README.md

This link is broken and doesn't appear to map to anything current.  I propose We remove this link.

_examples: README.md , Remove broken Config link.

---

plumbing/transport/internal/common/common.go
plumbing/transport/internal/common/common_test.go

Returning `nil` causes `handleAdvRefDecodeError` to fall back to `io.ErrUnexpectedEOF`.

fix: don't use the `firstErrLine` when it is empty

---

.github/workflows/git.yml
.github/workflows/test.yml
go.mod
go.sum

**Bumped Dependencies**
- github.com/ProtonMail/go-crypto to version 0.0.0-20230217124315-7d5c6f04bbb8.
- github.com/acomagu/bufpipe to version 1.0.4.
- github.com/go-git/go-billy/v5 to version 5.4.1.
- golang.org/x/crypto to version 0.6.0.
This PR includes an orthogonal commit that reduces the GitHub token permission used within the GH Actions.

Bump dependencies

---

.github/workflows/git.yml
.github/workflows/test.yml
Makefile
worktree_test.go

The `TestPullAdd` test uses `git` CLI to perform a commit.
Contributors with signing enabled globally would have their GPG
configuration being used to sign that test commit.
This behaviour was transparent for contributors that do not use
secure keys which requires physical confirmation.
The new behaviour disables GPG signing for that test, which was
not required as part of the test.
Removes the error messages: `Node.js 12 actions are deprecated`.
After the fix of data races in go-billy (go-git/go-billy/pull/28)
race detection can be enabled in go-git to ensure no new issues
go undetected.

ci: Bump GitHub actions, enable go test race detection and stop using developer's GPG keys during test execution

---

plumbing/transport/ssh/auth_method.go
plumbing/transport/ssh/common.go
plumbing/transport/ssh/common_test.go
plumbing/transport/ssh/upload_pack_test.go

Don't overwrite HostKeyCallback if one is provided.
Fixes: c35b8082c863 ("plumbing: transport/ssh, auto-populate ClientConfig.HostKeyAlgorithms. Fixes #411")
Fixes: https://github.com/go-git/go-git/issues/654
Signed-off-by: Ayman Bagabas <ayman.bagabas@gmail.com>

fix(ssh): unable to pass a custom HostKeyCallback func

---

storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/dotgit_test.go

In walkReferencesTree(), the filesystem is browsed recursively. After a folder is listed, each child element (directory, file) are inspected.
What can happen is that by the time we get to operate on the child element, it might have been deleted from the filesystem and we would get a PathError.
In the case of directories there was already a case to avoid bubbling up the error (we consider that there is no ref there, which is correct), but that was missing for files. This commit just apply the same logic.

dotgit: fix a filesystem race in Refs/walkReferencesTree

---

.github/workflows/git.yml
Makefile
_examples/sha256/main.go
config/config.go
options.go
plumbing/format/commitgraph/encoder.go
plumbing/format/config/format.go
plumbing/format/idxfile/decoder.go
plumbing/format/idxfile/encoder.go
plumbing/format/idxfile/idxfile.go
plumbing/format/index/decoder.go
plumbing/format/index/encoder.go
plumbing/format/packfile/encoder.go
plumbing/format/packfile/encoder_test.go
plumbing/format/packfile/scanner_test.go
plumbing/hash.go
plumbing/hash/hash.go
plumbing/hash/hash_sha1.go
plumbing/hash/hash_sha256.go
plumbing/protocol/packp/ulreq_decode_test.go
repository.go
storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/writers.go

The implementation includes an example that initializes a Git repository that is compatible with `git fsck` and can be used interchangeably with `git`.
The variable length for `plumbing.Hash` is defined at build time, blocked by tag `sha256`. This approach was a trade-off between keeping backwards compatibility while making progress towards supporting SHA256 with a small amount of changes.
Relates to  #706.

*: Add support for initializing SHA256 repositories

---

internal/url/url.go
internal/url/url_test.go
plumbing/transport/common_test.go

I found that a regression was added in this commit https://github.com/go-git/go-git/commit/db0e226d48285a0ae8cda7db05d2ca20d9000dc6.
Specifically, it dropped support for repositories without multipath (ex. `git@host:repo.git`). The package fails cloning this kind of repository with this error:
```
$ go run -- "git@host:repo.git"
Cloning "git@host:repo.git"...
Error: repository not found
```
This PR fixes it and it adds test cases to cover the intended functionality.

internal: Fix regression in scp-like match

---

config/config.go
options.go
repository.go
repository_test.go

Clone remote as a mirror. This fetches all remote refs, implies bare repository, and sets the appropriate configs.
Fixes: https://github.com/go-git/go-git/issues/293

git: add mirror clone option

---

plumbing/reference_test.go
storage/filesystem/dotgit/dotgit.go

In this PR I tweaked the parsing strategy of packed-refs to not continue if it is a single reference if it has already been found, which is very useful for repositories with thousands of references.
This reduces one iteration of references for loading all references, and also reduces memory allocations for a large number of references.

storage: filesystem/dotgit, Improve load packed-refs

---

options.go
worktree.go
worktree_test.go

Perform grep on both `*Repository` or `*Worktree`.
Fixes: https://github.com/go-git/go-git/issues/68

fix: git grep bare repositories

---

_examples/ls-remote/main.go
options.go
remote.go
remote_test.go

A new `PeelingOption` field was introduced into `ListOptions`. The new options
include the default (and backwards compatible) IgnorePeeled. Plus another
two variations which either only returns peeled references (`OnlyPeeled`), or
append peeled references to the list (`AppendPeeled`).
The ls-remote example was updated to align with upstream, in which peeled
references are appended to the results by default.
A new `ErrEmptyUrls` error is now returned when `List` or `ListContext` do not
receive a URL to work with, to improve overall execution flow.

git: Add support to ls-remote with peeled references. Fixes #749

---

repository.go
repository_test.go

This fixes calling clone with a branch name rather than a full spec.
This is to match calling `git clone -b <name> <repository>`

git: fix cloning with branch name

---

worktree_status.go
worktree_test.go

Checks if an ignored file was previously checked in.  If it was, then the file is not ignored matching native git behavior. Fixes #718

git: worktree, add check to see if file already checked in. Fixes #718

---

options.go
submodule.go
submodule_test.go

In order to allow shallow cloning for submodules we added the new depth option to the SubmoduleUpdateOptions. This option is then being used while fetching a submodule.

git: Add Depth to SubmoduleUpdateOptions

---

options.go
remote.go

The previous hard-coded 10 second value is too short for listing large repositories like https://gitlab.com/gitlab-org/gitlab

git: remote, add support for a configurable timeout.

---

plumbing/reference.go
repository.go
repository_test.go

Allow the initial branch of the repo to be configurable.
This also adds `plumbing.Main` as a convenience constant so that it could be used for anyone wishing to, instead of having to define themselves.
Replaces #727 as this is non-breaking.

git: Allow Initial Branch to be configurable

---

common_test.go
remote.go
remote_test.go

Also fixes https://github.com/go-git/go-git/issues/207
(Note this is another option instead of https://github.com/go-git/go-git/pull/766, but doesn't require populating the shallows map, it also adds an optimisation of not adding extra hashes to the have map that we know we aren't going to need for a shallow request)

git: Fix fetching after shallow clone. Fixes #305

---

plumbing/format/gitignore/dir.go
plumbing/format/gitignore/dir_test.go

My `.gitconfig` looks like this:
```
[core]
editor = nano
excludesFile = ~/.gitignore
autocrlf = input
ignorecase = false
```
and it cant load `~/.gitignore` because it is not absolute.

Replace user dir in path

---

remote.go

Depth of 1 is common, add an optimisation where we don't add the object to wants if we already have it and the required depth is 1.

git: don't add to wants if exists, shallow and depth 1

---

plumbing/format/gitignore/dir_test.go
plumbing/format/gitignore/pattern.go

plumbing: gitignore, fix incorrect parsing. Fixes #500

---

submodule.go
submodule_test.go

When doing update for a submodule that has an SCP style URL I'm getting the following error:
```
first path segment in URL cannot contain colon
```
The offender seems to be [this line of code](https://github.com/go-git/go-git/blob/7e345bb5e163a4badefb0c54da3a057dcde50ed6/submodule.go#L136). It tries to use the go standard library method for URL parsing which cannot parse SCP style URLs.
Testing:
I'll need a bit of help with writing an integration test (if needed) for this usecase - it seems we'll have to add an additional (change existing) submodule in one of the fixtures to use the SCP style URL.
Edit:
I've added a unit test that should be enough of a safety net for this small use case.

git: fix the issue with submodules having the SCP style URL fail due to the wrong URL parsing

---

options.go
repository.go
repository_test.go

This option matches the git clone option --shallow-submodules. 
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---no-shallow-submodules

git: add a clone option to allow for shallow cloning of submodules

---

plumbing/protocol/packp/advrefs_decode.go
plumbing/protocol/packp/advrefs_decode_test.go
plumbing/transport/http/common.go
remote.go

Git `v2.41.0` comes with [changes](https://github.com/git/git/commit/933e3a4ee205353d8f093d5dfcd226fa432c4e58) that breaks go-git's assumptions for when detecting empty repositories in HTTP transport.
Go-git expects a flush instead of the first hash line. Instead, a dummy `capabilities^{}` with zero-id is returned. The upstream change aims to allow for identifying the `object-format` even when cloning empty repositories.
Fixes the currently broken CI.
Relates to #229.

plumbing: http, Fix empty repos on Git v2.41+

---

plumbing/protocol/packp/uppackreq.go
plumbing/protocol/packp/uppackreq_test.go
plumbing/transport/internal/common/common.go

Note, this was broken in #311 where the check was only added to a single version of UploadPack (there are 3)

plumbing: packp, A request is not empty if it contains shallows. Fixes #328

---

common_test.go
repository.go
repository_test.go

Fixes #803.
Not much to say here, simply added a prefix "~/" check for path and handled the users home directory accordingly.

*: Handle paths starting with tilde

---

storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/dotgit_test.go

more background: since dec 2021 git team changed incoming dir naming template from "incoming-*" to "tmp_objdir-incomming-*": https://github.com/git/git/commit/b3cecf49eac00d62e361bf6e6e81392f5a2fb571
now go-git works properly if it is using in pre-receive hooks

storage: filesystem/dotgit, add support for tmp_objdir prefix

---

plumbing/transport/common.go
plumbing/transport/common_test.go

Fix host formatting for IPv6 adresses

plumbing: transport, handle IPv6 while parsing endpoint. Fixes #740

---

go.mod
go.sum

Closes #826
The go-git library is using a version of goproxy that's affected by CVE-2023-37788. This vulnerability has been fixed in elazarl/goproxy#502. To address this, this PR updates the goproxy dependency in go.mod.

Update goproxy dependency to fix CVE-2023-37788 vulnerability

---

worktree.go
worktree_status.go
worktree_test.go

do not exclude ignored filese from .gitignore in diffStagingWithWorktree when resetting worktree.

git: worktree, reset ignored files that are part of the worktree: Fixes #819

---

plumbing/transport/http/common.go
plumbing/transport/http/common_test.go
plumbing/transport/http/receive_pack.go
plumbing/transport/http/upload_pack.go

For diagnostics reasons we want to surface error messages coming from VCS providers. That's why we introduce the reason field to Err struct in http package. This field can be used by an end user of the library in order to better understand failures.
Context:
Recently ADO started responding with 5xx family of errors in certain cases (indicating an issue on their end) and since the library swallows errors there wasn't a way to understand what's going on.

plumbing: Do not swallow http message coming from VCS providers

---

options.go
repository.go
repository_test.go

Refactor `PlainInit` to call `PlainInitWithOptions`, and make `InitOptions` usable there.
Basically allows using the `DefaultBranch` option from #764  with `PlainInit`.

git: add PlainInitOptions.Bare and allow using InitOptions with PlainInitWithOptions

---

.github/workflows/stale-issues-bot.yaml

Due to the limited amount of active maintainers, adding a stale bot to concentrate the available maintainership on non stale PRs and issues.

*: Add bot to close stale issues

---

plumbing/format/commitgraph/encoder.go
plumbing/format/commitgraph/file.go

Since the build-tag sha256 was introduced the commit graph code should be switched to use hash.Size and only use a graph if it has the correct hash version for the version of go-git that is built.

plumbing: commitgraph, allow SHA256 commit-graphs

---

Makefile
internal/revision/parser_test.go
plumbing/format/config/decoder_test.go
plumbing/format/packfile/delta_test.go
plumbing/object/signature_test.go
plumbing/object/tree_test.go
plumbing/protocol/packp/uppackresp_test.go
plumbing/transport/common_test.go
utils/merkletrie/internal/fsnoder/new_test.go

`Fuzz` testing support using [go-fuzz](https://go.dev/security/fuzz) .

fuzzing :  fuzz testing support for oss-fuzz integration

---

plumbing/object/commit.go
plumbing/object/commit_test.go

project may use legacy encodings, not utf-8, if that, it will keep the encoding info in commit 'encodng' header. 
when we decode the commit object, we need to parse the encoding header, other part can re-code the commit message according to this header.

plumbing: parse the encoding header of the commit object

---

.gitignore
COMPATIBILITY.md
options.go
plumbing/storer/object.go
plumbing/storer/object_test.go
repository.go
repository_test.go
storage/filesystem/dotgit/dotgit.go
storage/filesystem/storage.go
storage/memory/storage.go
storage/transactional/object.go

--shared
When the repository to clone is on the local machine, instead of using hard links, automatically setup .git/objects/info/alternates to share the objects with the source repository. The resulting repository starts out without any object of its own.

add clone --shared feature

---

plumbing/protocol/packp/srvresp.go
plumbing/protocol/packp/srvresp_test.go

plumbing: protocol/packp, Add validation for decodeLine

---

.github/workflows/pr-validation.yml

Adds automation to confirm that the commit messages align with the contributing guidelines.

build: Add github workflow to check commit message format

---

plumbing/transport/internal/common/common.go
plumbing/transport/internal/common/common_test.go
plumbing/transport/internal/common/mocks.go

Instead of simply returning the first line that the remote returned, go-git now actively searches all of stderr for lines that may contain a more actionable error message and returns that.
This is helpful in cases where the first line doesn't really indicate the actual issue, e.g. in the output of the GitLab server (over SSH):
```
$ ssh git@gitlab.com "git-receive-pack 'foo/bar'"
remote: 
remote: ========================================================================
remote: 
remote: ERROR: The project you were looking for could not be found or you don't have permission to view it.
remote: 
remote: ========================================================================
remote: 
```
In addition, this change adds a case to map the GitLab-specific error message to an ErrRepositoryNotFound …

Improve handling of remote errors

---

go.mod
go.sum
plumbing/format/commitgraph/v2/chunk.go
plumbing/format/commitgraph/v2/commitgraph.go
plumbing/format/commitgraph/v2/commitgraph_test.go
plumbing/format/commitgraph/v2/encoder.go
plumbing/format/commitgraph/v2/file.go
plumbing/format/commitgraph/v2/memory.go
plumbing/object/commitgraph/commitnode.go
plumbing/object/commitgraph/commitnode_graph.go
plumbing/object/commitgraph/commitnode_object.go
plumbing/object/commitgraph/commitnode_walker_author_order.go
plumbing/object/commitgraph/commitnode_walker_ctime.go
plumbing/object/commitgraph/commitnode_walker_date_order.go
plumbing/object/commitgraph/commitnode_walker_helper.go
plumbing/object/commitgraph/commitnode_walker_test.go
plumbing/object/commitgraph/commitnode_walker_topo_order.go

This PR adds in support for generation v2 support and a couple of new walkers to match --date-order etc options on log.

plumbing: commitgraph, Add generation v2 support

---

.github/workflows/pr-validation.yml
remote.go
remote_test.go

In remote.updateLocalReferenceStorage, this commit updates a check to see if the reference is for a branch (in refs/heads) to checking the reference is not a tag. This change ensures that the subsequent fast-forward only handling clauses apply to references that are not standard branches stored in refs/heads.
I'm still missing tests etc here. If this fix makes sense, happy to work towards that (though I might need some pointers again).
#874

remote: Flip clause for fast-forward only check

---

plumbing/transport/ssh/common.go
plumbing/transport/ssh/common_test.go

Fixes #900 
Root Cause:
variable `err` is being shadaowed by another variable declaration inside the scope when proxy server url is set. When checking for any error during the `Dial` operation, the outer scope variable `err` is used and  it would always be `nil`. Thus the actual error gets ignored and this makes the code execution to proceed with a `nil` connection which eventually fails with a panic caused due to `nil` pointer dereference.
Fix:
Change the variable name for the error to `dialErr` in the outer scope, so that the variable shadowing does not happen.

plumbing: transport/ssh, Fix nil pointer dereference caused when an unreachable proxy server is set. Fixes #900

---

COMPATIBILITY.md
cli/go-git/main.go
cli/go-git/update_server_info.go
internal/reference/sort.go
plumbing/serverinfo/serverinfo.go
plumbing/serverinfo/serverinfo_test.go

This adds UpdateServerInfo along with a new go-git command to generate info files to help git dumb http serve refs and their objects.
This also sorts the refs by name before returning them. Not sure if this would break things :/
Docs: https://git-scm.com/docs/git-update-server-info
Fixes: https://github.com/go-git/go-git/issues/731

Implement upload-server-info

---

plumbing/format/packfile/parser.go
plumbing/format/packfile/patch_delta.go
repository_test.go
storage/filesystem/object.go

Previously, as part of building the index representation, the `resolveObject`
func would create an interim `plumbing.MemoryObject`, which would then be
saved into storage via `storage.SetEncodedObject`. This meant that objects
would be unnecessarily loaded into memory, to then be saved into disk.
The changes streamlines this process by:
- Introducing the `LazyObjectWriter` interface which enables the write
operation to take place directly against the filesystem-based storage.
- Leverage multi-writers to process the input data once, while targeting
multiple writers (e.g. hasher and storage).
An additional change relates to the caching of object info children within
`Parser.get`. The cache is now skipped when a seekable filesystem is being
used.
The impact of the changes can be observed …

plumbing: Optimise memory consumption for filesystem storage

---

internal/trace/trace.go
internal/trace/trace_test.go
plumbing/format/pktline/encoder.go
plumbing/format/pktline/scanner.go

This adds a generic tracing package to log messages to output if the target is set.

git: add tracer package

---

plumbing/transport/internal/common/common.go
remote.go
worktree_test.go

If we have all what we asked for, finish the session and handle error.
This is equivalent of git "Already up to date." message.
Fixes: https://github.com/go-git/go-git/issues/328
Fixes: https://github.com/go-git/go-git/issues/638
Fixes: https://github.com/go-git/go-git/issues/157

plumbing: fix empty uploadpack request error

---

utils/merkletrie/filesystem/node.go
utils/merkletrie/filesystem/node_test.go

Fixing #312.
I used `osfs.New(td)` in the tests with an os.MkdirTemp because I have no clue how to create a socket in the memfs.

Ignore ModeSocket files

---

plumbing/format/pktline/error.go
plumbing/format/pktline/error_test.go
plumbing/format/pktline/scanner.go
plumbing/protocol/packp/common.go
plumbing/protocol/packp/gitproto.go
plumbing/protocol/packp/gitproto_test.go
plumbing/transport/git/common.go
plumbing/transport/internal/common/common.go
plumbing/transport/internal/common/common_test.go

Pkt-line defines an error-line format to send errors from/to the client or server. This is mainly used with the git transport since it doesn't have a dedicated stderr channel but can also be used with both ssh and file transports.
This also moves the git-proto-request pktline type into a struct.

Respect pktline error-line errors

---

plumbing/object/patch.go
plumbing/object/patch_stats_test.go

Diff has handled renames by default since 2020. This change sets Name for the renamed file in a manner similar to diffstat.

plumbing: object, enable renames in getFileStatsFromFilePatches

---

cli/go-git/go.mod

Fix the cli module package name
Fixes: https://github.com/go-git/go-git/issues/952
Fixes: https://github.com/go-git/go-git/pull/914

git: cli, fix module name

---

utils/merkletrie/filesystem/node.go

The main motivation behind this change is to speed up status operation. Currently it's very slow, especially for repositories with lots of ignored files (e.g. node.js repository with node_modules directory). One of the reasons for this slowness is the fact that traversing filesystem involves calculating file hashes for all files, even if those hashes are not needed in the end because the files are in gitignore.
On my machine, for a random repository with sizable (ignored) node_modules directory this  changes bring the execution time for Worktree.Status from ~3.5s to ~1.4s. This is still very slow, but a significant improvement.
A better fix (instead of or in addition to this one) would be to avoid traversing ignored files in the first place. However, such change seem to be more intrusive …

Calculate filesystem node's hash lazily.

---

utils/merkletrie/filesystem/node.go

This reflects the lazy hash calculation and the implications of this.

utils: update comment in node.go's Hash()

---

options.go
worktree_commit.go
worktree_commit_test.go

This change adds a new `crypto.Signer` option to `CommitOptions` as an alternative to `SignKey` to allow alternative commit signers to be used. This change does not add other signing or verification methods (e.g. ssh, x509, gitsign), but gives callers the ability to start adding their own signing implementations.
This differs from https://github.com/go-git/go-git/pull/705 by using the stdlib `crypto.Signer` interface instead of defining a new `ObjectSigner` interface. We could go with that approach if we want, but using a []byte based approach means that Signer implementations do not need to be aware of how commit encoding works (which is closer to [git's sign_buffer implementation](https://github.com/git/git/blob/a54a84b333adbecf7bc4483c0e36ed5878cac17b/gpg-interface.h#L71)).
Part of …

Add crypto.Signer option to CommitOptions.

---

options.go
worktree_commit_test.go
worktree_status.go
worktree_test.go

Worktree.AddWithOptions: add skipStatus option when providing a specific path to add.
This will skip the git status check which might takes long time in a large repositories. 
This should Address https://github.com/go-git/go-git/issues/993

Worktree.AddWithOptions: add skipStatus option when providing a specific path

---

_examples/README.md

- Fixing dead links on readme and added link for the missing example

_example: fix 404 link and added ssh-agent clone link

---

plumbing/format/gitattributes/attributes.go
plumbing/format/gitattributes/dir.go

`gitattributes.ReadAttributesFile(...)` currently doesn't close the successfully opened file causing troubles especially on Windows systems.
This PR fixes this issue.
Furthermore I added a tiny optimisation to not read the `.gitattributes` file completely to memory before processing it but to use a `bufio.Scanner` to process it line by line.
See issue #1017

plumbing: format/gitattributes, close file in ReadAttributesFile

---

Makefile
_examples/checkout-branch/main.go
_examples/common_test.go

This PR adds a `checkout-branch` example and some minor fixes for testing.
It took me a while to figure out how to check-out a branch in my cloned repo, and thought this might save some time and could be useful helping someone else to do so.
Originally, after some digging, I used the method used in this issue: https://github.com/src-d/go-git/issues/777
However, realised it was copying all references, and causes faulty HEAD references in some cases (git "refname HEAD is ambiguous" warning I think, but can't remember exactly now).  Couldn't find any examples of fetching a single branch, hence thought this might be useful.

checkout-branch example

---

options.go
signer.go
signer_test.go
worktree_commit.go

crypto.Signer was incorrectly used before. Signer documentation says that Sign should be used on digests, whereas we are using this on message bodies. We want this interface to use message bodies, since different signing formats (gpg, ssh, x509) usually chose to represent this as a specific format (e.g. gitsign/smimesign use pkcs7) before taking a digest and signing.
To fix this, create our own Signer interface (+ signableObject borrowed from #705) that describes more accurately what we want. As before, the expectation is that signer implementations only need to worry about acting on encoded message bodies rather than needing to encode objects themselves.
This is technically a breaking change from the previous Signer implementation (introduced in #996), but since this is new and hasn't …

Signer: fix usage of crypto.Signer interface

---

options.go
remote.go
remote_test.go

This PR adds `prune` option to the `Fetch` command.
Fixes #316

remote: fetch, adds the prune option.

---

plumbing/object/commit_walker_path.go
plumbing/object/commit_walker_test.go

This PR fixes #191.
Because the `parentCommit` in `(*commitPathIter).getNextFileCommit()` is nil if `currentCommit` is initial commit, 
I modified the condition to pass when parent == nil.

plumbing: object, Make first commit visible on logs filtered with filename. Fixes #191

---

worktree.go
worktree_test.go

I didn't dig into the specific case that was triggering this, but we did have a panic in our production system.

git: worktree, Don't panic on empty or root path when checking if it is valid

---

plumbing/object/tree.go
plumbing/object/tree_test.go

if there is '\x00' in filename, Encode() will produce a malformed object.
also add some checks for entry order

plumbing: object, check legitimacy in (*Tree).Encode

---

plumbing/object/commit_walker_path.go
plumbing/object/treenoder.go

Connected to: #811
So, I've been digging this issue. Then I found that `object.(*treeNoder).NumChildren` was the one that is consuming most of cpu time.
After some investigtion, I figured out that treeNoder.children field is documented as "memoized", but none of the code actually saves its result.
```go
type treeNoder struct {
parent   *Tree  // the root node is its own parent
name     string // empty string for the root node
mode     filemode.FileMode
hash     plumbing.Hash
children []noder.Noder // memoized <- here!!
}
```
So I modified the code to save the result of `transformChildren()`. And here's how it is changed.
> Ran on Apple M2 processor
Output:
```
$ go run main.go
2024/03/10 13:53:55 cloning repository
2024/03/10 13:54:01 git log start
2024/03/10 13:54:33 time elapsed: …
```

plumbing: object, Optimize logging with file.

---

plumbing/object/commit_test.go
plumbing/object/patch.go
plumbing/object/patch_test.go

This PR addresses a panic issue in the patch.printStats function. The current implementation closely follows the original one written in C. 
Connected to: #177 
Here are a few examples of the new output:
```
file1 | 0
file1 | 1 +
.github/workflows/git.yml | 2 +-
.github/workflows/git.yml | 2 +-
cli/go-git/go.mod         | 8 ++++----
.github/workflows/git.yml |   6 +++---
worktree.go               | 107 +++++++++++++++++++++++++++++++++++++++++++++++++++++
worktree_test.go          |  75 +++++++++++++++++++++++++++++++++++++++++++++++++++++
.github/workflows/git.yml |   6 +++---
worktree.go               | 324 ++++++++++++++++++-----------------------------------
worktree_test.go          | 350 ++++++++++++-----------------------------------------
```

plumbing: no panic in printStats function. Fixes #177

---

COMPATIBILITY.md
options.go
remote.go
repository.go
repository_test.go

Introduces the `Merge` function for merging branches in the codebase.
Currently, the function only supports `FastForwardMerge` strategy, meaning it can efficiently update the target branch pointer if the source branch history is a linear descendant.
Support for additional merge strategies (e.g., three-way merge) will be added in future commits.
This PR expands and supersedes the work from #442. Thanks @john-cai for the initial contribution.
Fixes https://github.com/go-git/go-git/issues/905. 
Relates to https://github.com/go-git/go-git/issues/942.

git: Implement Merge function with initial `FastForwardMerge` support

---

plumbing/transport/http/common.go
plumbing/transport/http/common_test.go
plumbing/transport/http/transport.go

The decision to change the name of these fields came from reading the code further down in the scope and not being clear what `c.c` means.
This also aligns it with the convention from other structs in the same file like e.g. the `session` struct:
```
type session struct {
auth     AuthMethod
client   *http.Client
endpoint *transport.Endpoint
advRefs  *packp.AdvRefs
}
```

Replace short field names with more descriptive ones.

---

plumbing/format/index/decoder.go
plumbing/format/index/decoder_test.go
plumbing/format/index/encoder.go
storage/filesystem/index.go

See the 2 individual commits.
This fix might cause some existing repos to fail now, because go-git did not properly fail on `link` extensions (split index). I assume it's fine to fail, as this extension is mandatory anyway and behaviour is actually undefined/buggy when handling of it is skipped.
Fixes: #299

Properly support skipping of non-mandatory extensions 

---

plumbing/protocol/packp/filter.go
plumbing/protocol/packp/filter_test.go
plumbing/protocol/packp/ulreq.go
plumbing/protocol/packp/ulreq_encode.go
plumbing/protocol/packp/ulreq_encode_test.go

This allows lower-level `go-git` package consumers to interact with registries supporting `filter` capability and partially fetch objects given a `Filter` specification.
Related: https://github.com/go-git/go-git/issues/713.

plumbing: protocol/packp, client-side filter capability support

---

plumbing/protocol/packp/sideband/demux.go
plumbing/protocol/packp/sideband/demux_test.go

Canonical Git implementation terminates the sideband stream with a flush. If the demux scanner is not terminated, it can hang the connection. Returns io.EOF when encountering a flush pkt.
https://github.com/git/git/blob/master/upload-pack.c#L460

plumbing: fix sideband demux on flush

---

storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/dotgit_test.go

When reading the repository references from DotGit, the HEAD reference should always come first.
This mimics the behavior of `git show-ref --head`

storage: dotgit, head reference usually comes first

---

example_test.go

Hi, 
Just wanted to say I think this library is super cool and I really appreciate the hard work you guys do.
I saw that some methods are missing examples so I wanted to give back and write an example for the Branches() function.
I read the [contributing guidelines](https://github.com/go-git/go-git/blob/bdb35e1950b5829c88df134810a0aa9a7da9bc22/CONTRIBUTING.md) to see how I should format my commit message and I ended up going with using `git` as the prefix for the commit message because the example is tied to that package. Let me know if this is right :)

git: Added an example for Repository.Branches

---

repository_test.go
worktree_commit.go
worktree_commit_test.go
worktree_test.go

Changed condition of checking empty commit from `count of entries == 0` to `createdHash == parentHash`.
There was an edge case where the given commit is initial commit and worktree has no entries. So I made another control branch to check it.
I'm not aware of other edge cases it might have. If there is one, please let me know.
Connected to #723

git: worktree_commit, Modify checking empty commit. Fixes #723

---

internal/test/checkers.go
plumbing/transport/http/common.go
plumbing/transport/http/common_test.go
plumbing/transport/http/upload_pack_test.go
plumbing/transport/test/receive_pack.go

This attempts to address https://github.com/go-git/go-git/issues/1097.
A few notes:
* The underlying testing library doesn't have an `errors.Is` check, so I went and implemented one in `internal/test`. Not sure that's the right spot to put it.
* The `internal/test.ErrorIs` can be removed if https://github.com/go-check/check/issues/139 gets fixed.
* I kept the `ErrorMatches` string check in the places I found it.
* I didn't provide tests for `internal/test.ErrorIs`, would you like them?

plumbing: transport/http, Wrap http errors to return reason. Fixes #1097

---

go.mod
go.sum

This PR fixes a [CVE](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMELAZARLGOPROXY-5783247) in goproxy.

build: bump github.com/elazarl/goproxy from v0.0.0-20230808193330-2592e75ae04a to v0.0.0-20240618083138-03be62527ccb

---

options.go
worktree.go
worktree_status.go
worktree_test.go

This introduces an `All` option which, when enabled, removes files even when they are excluded by gitignore. This is equivalent to `git clean` with the `-x` flag but without the ability to customize the excluded patterns as provided by the `-e` flag.

Add option approximating `git clean -x` flag.

---

options.go
worktree.go
worktree_status.go
worktree_test.go

Reverts go-git/go-git#995 as it broke the master branch.

Revert "Add option approximating `git clean -x` flag."

---

storage/filesystem/dotgit/dotgit.go
storage/filesystem/dotgit/dotgit_test.go

If a reference exists in the packed refs file but not in the actual refs folder, we need to fall back to reading the pack refs file when storing the reference.
This happens because by the time we are storing the reference, we open the file with write permissions and read from it. At that point, if the file is empty, we still need to read the valid reference. Otherwise, it will read 0, and assume that the references do not match (because the old value was read from the packed file).
Relates to https://github.com/go-git/go-git/issues/37

Fix reference updated concurrently error for the filesystem storer

---

plumbing/format/gitignore/dir.go
plumbing/format/gitignore/dir_test.go

Stop loading .gitignore files from ignored directories, as this can cause files to be included that should not be.
See https://git-scm.com/docs/gitignore#_pattern_format

plumbing: gitignore, Fix loading of ignored .gitignore files.

---

plumbing/transport/ssh/auth_method.go
plumbing/transport/ssh/auth_method_test.go
plumbing/transport/ssh/common.go

The recently released skeema/knownhosts v1.3.0 introduced a `HostKeyDB` type that extends the `HostKeyCallback` functionality to support @cert-authority algorithms in its key `HostKeyAlgorithms` discovery functionality.
`known_hosts` files may contain lines with @cert-authority markers to represent a certificate instead of a key. If a git remote uses cert authorities as the preferred host identification mechanism, the functionality added in skeema/knownhosts v1.3.0 is needed so that go-git can interact with this remote and verify it.
See https://github.com/skeema/knownhosts/pull/9 for details.

plumbing: transport/ssh, Add support for SSH @cert-authority.

---

.github/workflows/test.yml

A new test has been added in order to verify that all code under
_examples is up to date and has not broken due to API changes.
This test runs as the last step of the test.yml CI workflow.
Closes https://github.com/go-git/go-git/issues/912.

build: run example tests during CI workflow

---

storage/filesystem/object.go
storage/filesystem/object_test.go

I noticed the `ObjectStorage.getFromUnpacked` function has an object cache, but it is never actually used to resolve any objects. I found that when a new object is being put into cache its hash (which is used as the cache key) is always zero, which makes future loads of that same object always miss when trying the cache. See the debugger screenshots in the expandable sections.
<details>
<summary>Hash of the queried object at the check cache point</summary>
</details>
<details>
<summary>Hash of the loaded object when it's being put into cache (it's zero)</summary>
The hash is later used as cache key:
```Go
func (c *ObjectLRU) Put(obj plumbing.EncodedObject) {
...
objSize := FileSize(obj.Size())
key := obj.Hash()
...
```
</details>
<details>
<summary>Hash of the loaded object when it's …

storage: filesystem, Fix object cache not working due to uninitialised objects being put into cache

---

remote.go
remote_test.go

This fixes fetching commits that have a reference to them but are not in the pack files.

git: Fix fetching missing commits

---

plumbing/format/packfile/delta_index.go

At the beginning of `findMatch()`, there exist two checks for `len(tgt) < tgtOffset+s` and `len(src) < blksz`.
Simplify the code by removing the inverse checks `len(tgt) >= tgtOffset+s` and `len(src) >= blksz` down below.

plumbing: format/packfile, remove duplicate checks in findMatch()

---

status.go
worktree_status.go
worktree_test.go

When using the lib I have also faced this problem #119. After looking into the code my understanding is that we were initializing the `status` empty before making the diff operations. This causes an empty status object when no diff is encountered. Which lead us to get `Untracked` status for committed files.
I manage to solve this by adding an initialization method for our `status` that iterates over the `storer` index building an initial status with all the unmodified files included. This way, when we use `status.File` it will find it on the map and will return correctly the `Unmodified` status.
Fix #119

git: worktree, Fix file reported as `Untracked` while it is committed

---

worktree_status.go
worktree_status_test.go

worktree.Add does not add a modified file correctly, while git add works as expected #1003
There was a check at `doUpdateFileToIndex` that would consider any file with executable permissions as an executable.
This is wrong and should be fixed. 
Despite this, even if a file is an executable, it should be able to be staged; this is the default behavior of `git CLI`. 
Add an extra check for the executable file that allows the size of `*index.Entry` to be set.

plumbing: filemode, Remove check for setting size of .git/index file 

---

plumbing/transport/file/client.go
repository_windows_test.go

Fixes #415
A file: url for windows looks something like `file:///d:/directory/file.txt` . Once parsed, the Path from the URL has `/d:/directory/file.txt`. This is not a valid path to the operating system. In order for it to be meaningful, the leading slash needs to be removed.

adjust path extracted from file: url on Windows

---

plumbing/transport/server/loader.go
plumbing/transport/server/loader_test.go

This is a simple fix to the fs loader that allows loading of non-bare repositories on the filesystem. Previously only bare repositories could be found due to the config check, now it also checks for the default .git directory.
Also kills the TestLoadIgnoreHost case since it was duplicated with TestLoad.
Doesn't use the git dir constant due to an import conflict

fix: allow discovery of non bare repos in fsLoader

---

plumbing/server/loader.go
plumbing/server/loader_test.go

(cherry picked from commit 36756c91730bb3ccd0982703c90760a3621caf28)
cherry-picked based on https://github.com/go-git/go-git/pull/1170

plumbing: allow discovery of non bare repos in fsLoader

---

config/config.go
config/config_test.go
remote.go

I am not sure how far this goes with finally fixing #489, but it certainly shouldn’t make things worse.
We now consider also `pushurl` values in the repository config

Consume push URLs when they are provided

---

config/config.go
config/config_test.go
remote.go

Rebase of https://github.com/go-git/go-git/pull/1191 for the [v6-exp](https://github.com/go-git/go-git/tree/v6-exp) branch.

v6: Consume push URLs when they are provided

---

common_test.go
options_test.go
plumbing/format/packfile/parser_test.go
plumbing/transport/file/common_test.go
plumbing/transport/git/common_test.go
plumbing/transport/http/common_test.go
plumbing/transport/ssh/internal/test/proxy_test.go
plumbing/transport/ssh/proxy_test.go
plumbing/transport/ssh/upload_pack_test.go
remote_test.go
repository_test.go
repository_windows_test.go
storage/filesystem/dotgit/dotgit_test.go
storage/filesystem/dotgit/repository_filesystem_test.go
storage/filesystem/dotgit/writers_test.go
submodule_test.go
utils/merkletrie/filesystem/node_test.go
worktree_commit_test.go
worktree_test.go

This PR removes all the usage of `TempDir` and replaces it with gocheck's `MkDir`. It removes the requirement of cleanup functions. 
Note that I haven't removed them from examples directory as they are not tests. 
Fixes: #807

*: use gocheck's MkDir instead of TempDir for tests. Fixes #807

---

COMPATIBILITY.md
_examples/common_test.go
_examples/sparse-checkout/main.go
repository_test.go
worktree.go
worktree_test.go

The operation applying sparse reset directories was performed before modifying indexes.
Therefore, It was overwritten by index modification.
So I moved the logic to perform after index modification.
This should fix #90.

git: worktree, Fix sparse reset. Fixes #90

---

.github/workflows/test.yml
plumbing/format/pktline/pktline.go

Previously, the trace would output the raw packfile data, which wasn't very useful. This change replaces the binary data with '[ PACKDATA ]' instead of the raw data, resulting in lines such as the following:
```
22:31:38.937878 pktline.go:224: packet: < 6005 [ PACKDATA ]
22:31:38.943047 pktline.go:224: packet: < 4005 [ PACKDATA ]
22:31:38.943865 pktline.go:224: packet: < 2005 [ PACKDATA ]
```

[v6-exp] plumbing: Improve PACK trace by redacting binary data

---

internal/transport/test/upload_pack.go
plumbing/protocol/packp/common.go
plumbing/protocol/packp/srvresp.go
plumbing/protocol/packp/srvresp_test.go
plumbing/protocol/packp/ulreq.go
plumbing/protocol/packp/ulreq_decode.go
plumbing/protocol/packp/ulreq_decode_test.go
plumbing/protocol/packp/uppackreq.go
plumbing/protocol/packp/uppackresp.go
plumbing/protocol/packp/uppackresp_test.go
plumbing/revlist/revlist.go
plumbing/server/server.go
plumbing/transport/common.go
plumbing/transport/transport.go
plumbing/transport/transport_test.go

I push to v6 (because I use it on my project) but I think it should work on v5.
Should close https://github.com/go-git/go-git/issues/647 (at least on my project).
I'm not sure why, but when I add `ar.Capabilities.Add("multi_ack")` in my project I can delete the `Capabilities.Add("no-thin")` capability.

server: uploadpack, implement multi_ack capability

---

plumbing/object/tree.go

Resolves https://github.com/go-git/go-git/issues/725
I spent a few days trying to figure out why pushing produces an opaque error message from the remote.
It turned out that trees I had created needed to be sorted.
This PR adds a comment at the function used for encoding trees into a storer, which ensures that developers will encounter it when using the tree API.

add comment preventing people from creating invalid trees

---

plumbing/format/index/encoder.go
plumbing/format/index/encoder_test.go

Hello,
With this pull request, Go-Git no more returns ErrUnsupportedVersion error when updating a version 4 .git/index file.

plumbing: Properly encode index version 4

---

worktree.go
worktree_test.go

Fix a bug where `Worktree.Reset()` and `Worktree.Restore()` with a `Files` option will skip over files that are in a subfolders.

Fix reset files in subfolders

---

plumbing/format/pktline/scanner.go
plumbing/format/pktline/scanner_test.go

Hello,
At work, I use a homemade git client implemented using Go-Git v5.12.
This client tries to clone repos hosted on a gitolite instance through http protocol.
A gitweb server handle the communication between my client and the gitolite server.
When the gitolite server grants access to the repository, it returns such pktlines in its answer:
001e# service=git-upload-pack
000000b5ab0ed9bd726e63e0679491160be72aaae876838b HEADmulti_ack thin-pack side-band side-band-64k ofs-delta shallow no-progress include-tag multi_ack_detailed no-done agent=git/[1.8.3.1](http://1.8.3.1/)
The length of first pktline (0x001e) is correctly parsed by Go-Git and the clone is done as expected.
However, when the gitolite server doesn't grant access to the repository, it returns such pktlines in its answer:
001E# …

pktline : accept upercase hexadecimal value as pktline length information

---

options.go
plumbing/object/commit_walker_limit.go
plumbing/object/commit_walker_test.go
repository.go

I believe it would be a nice filter parameter if we can limit the logs with the target hash along with time filter. 
what I like to see in this lib is something similar to ancestry path in git cli
```bash
git rev-list --ancestry-path 7b4a07a..ecf5891
```
then we should be able to select a path on the git tree by setting from/to hash 
```
__D     
/          
____B ___E___H
/          \__F
A             
\___ C
```
if I wanna select `HEB` we set `from: H, To: B`
wdyt?

plumbing: object, limit logs by trailing hash 

---

plumbing/format/objfile/common_test.go
plumbing/format/objfile/reader_test.go
plumbing/format/objfile/writer_test.go

plumbing: format/objfile, gocheck to testify migration. Fixes #1292

---

plumbing/protocol/version.go

The undefined constant must come after the iota. Otherwise, the iota will start from 1 instead of 0.

plumbing: protocol, fix undefined constant

---

plumbing/protocol/version.go
plumbing/transport/version.go
plumbing/transport/version_test.go

This adds two functions to the transport package to determine the protocol version for the client and server. The DiscoverVersion function reads the first pktline from the reader to determine the protocol version. This is usually used by the client-side.
The DiscoverProtocolVersion function tries to find the version parameter in the protocol string. This expects the protocol string from the GIT_PROTOCOL environment variable. This is used by the server-side.
This is based on https://github.com/go-git/go-git/pull/1332

plumbing: transport, determine protocol version

---

plumbing/format/pktline/pktline.go
utils/trace/trace.go

When tracing packet data, quote the data to make it easier to distinguish between the data and the length field and avoid escape sequences in the output that might be misinterpreted.
Before:
```
15:19:00.195792 pktline.go:20: packet: > 006e want f5c9cd905f3a9eeba77fdd1a522b1aa4cb79fa49 multi_ack_detailed side-band-64k ofs-delta agent=go-git/5.x
15:19:00.217529 pktline.go:224: packet: < 00f5 VLdLUFGiGDT
bj4~F43i
9^qe?.D`\r*r1y{zQr9{?=HHe
㶷K2=EL-Ԯu@{
```
After:
```
15:08:08.668554 pktline.go:20: packet: > 006e "want f5c9cd905f3a9eeba77fdd1a522b1aa4cb79fa49 multi_ack_detailed side-band-64k ofs-delta agent=go-git/5.x\n"
15:20:16.778797 pktline.go:224: packet: < 00f5 "[ PACKDATA ]"
```
Sideband:
upstream
```
15:33:17.289680 pkt-line.c:86           packet:     sideband< \2Compressing objects: …
```

plumbing: pktline, quote packet data in trace

---

storage/filesystem/dotgit/dotgit.go

Relates to https://github.com/go-git/go-git/issues/1342.

storage: filesystem/dotgit, Enforce timeout when trying to acquire lock

---

plumbing/transport/ssh/auth_method.go
plumbing/transport/ssh/auth_method_test.go
plumbing/transport/ssh/common.go

Reverts go-git/go-git#1157 due to #1341.

Revert "plumbing: transport/ssh, Add support for SSH @cert-authority."

---

internal/reference/refs.go
plumbing/protocol/packp/packp.go
plumbing/protocol/packp/srvresp.go
plumbing/protocol/packp/uphav.go
plumbing/transport/negotiate.go
plumbing/transport/serve.go
plumbing/transport/ssh/knownhosts/knownhosts.go
plumbing/transport/upload_pack.go
remote.go

This adds support for multi-ack and multi-ack-detailed capabilities in
the transport package. The support includes both the client and server.
This works by properly implementing the negotiation algorithm where the client and server can send/receive multiple upload-haves and server-response requests. The implementation follows canonical git sending 32 have lines per compute step to find the optimal packfile.
Related: https://github.com/go-git/go-git/commit/2ebd65f9d532401606d9ea16657fb6c6c42f3df5
Related: https://github.com/go-git/go-git/pull/1204
Based on: https://github.com/go-git/go-git/pull/1303 and https://github.com/go-git/go-git/pull/1337

refactor transport: plumbing: transport, support multi-ack and multi-ack-detailed capabilities (3/5)

---

plumbing/protocol/packp/advrefs_encode.go
plumbing/protocol/packp/inforefs.go
plumbing/transport/http/common.go
plumbing/transport/http/dumb.go
storage/filesystem/object.go

This adds support to the HTTP dumb protocol described in
https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols
Fixes: https://github.com/go-git/go-git/issues/492
Based on: https://github.com/go-git/go-git/pull/1303 and https://github.com/go-git/go-git/pull/1337

refactor transport: plumbing: transport/http, support http dumb protocol (4/5)

---

plumbing/transport/http/common.go

Fixes: #883 
Makes sure the transport uses correct `userAgent` instead of hardcoded `git/1.0`

plumbing: use the correct user agent string. Fixes #883

---

options.go
remote.go
repository.go
repository_test.go

This PR adds Filter support for git clone and fetch. #713 
I see an open PR #1108 that implemented this for fetch but was left open somehow. This is a more complete version of #1108.

git: fetch and clone --filter support

---

.github/workflows/cifuzz.yml
.github/workflows/codeql.yml
.github/workflows/git.yml
.github/workflows/pr-validation.yml
.github/workflows/stale-issues-bot.yaml
.github/workflows/test.yml
CONTRIBUTING.md

Recently both `master` and `v6-exp` branches were frozen. Two new branches were created to replace them:
- `releases/v5.x` the new maintenance branch for the V5 version.
- `main` is the new development branch, which is focusing on the V6 release.
The GitHub Workflows, and the contributing guideline, were changed to align with the new branch strategy.

build: Update branch strategy

---

config/config_test.go
config/url.go
config/url_test.go

breaking change to config.URL to support multiple insteadOf keys in configuration.
this fixes https://github.com/go-git/go-git/issues/862 and https://github.com/go-git/go-git/issues/863
this is a rebase of https://github.com/go-git/go-git/pull/864 -- you can close that PR

config: url, breaking change to support multiple insteadOf keys in configuration

---

plumbing/format/packfile/parser.go
plumbing/format/packfile/parser_test.go

A delta can reference a delta-ref we need to process them before delta.

plumbing: packfile parser process deltaRef before deltaObj in thin pack

---

README.md

Why? Because some people see "legal issues" and think "uh oh... a dark cloud is looming over this project now." Providing a link to more context to dispel the reflexive negative reaction to the words "legal issues" seems like a good idea. The GitHub comment was the best that I could find. If there's a better summary somewhere then update this link.

Add link to comment about the "legal issues"

---

plumbing/format/commitgraph/doc.go
plumbing/format/commitgraph/file.go
plumbing/format/commitgraph/v2/doc.go
plumbing/format/commitgraph/v2/file.go

Not 100% sure, but I'm guessing this new file is what was originally targeted

doc: Fix dead commit-graph-format links

---

remote.go
remote_test.go

When comparing the expected behaviour versus upstream git cli, it became clear that the tests expected all tags to be pulled - without actually setting that. This is a change in behaviour which will be introduced in v6, whereby Fetch is not expected to return all tags by default.
The git commands used for testing were:
```
git clone --no-checkout --bare  https://github.com/git-fixtures/tags.git /tmp/tags
cd /tmp/tags
git fetch origin '+refs/heads/*:refs/remotes/origin/*'
```
Based on the above, the test was amended to actively request for all tags to be returned.
This change has been tagged as breaking to reflect the previously made change that required it.
The test was failing due to a recently introduced optimisation, which skipped getting a commit if the reference was already known. …

Fix tests TestFetchOfMissingObjects and TestFetchWildcardTags

---

plumbing/storer/reference.go

currently we can return no error if r is nil

plumbing: fix err return in ResolveReference

---

internal/trace/trace.go
main_test.go
utils/trace/trace.go

This moves the trace initialization to the internal package and makes it opt-in instead of automatic. It also enables tracing on test runs by default.

internal: trace, read trace target from env

---

plumbing/protocol/packp/capability/capability.go
plumbing/transport/serve.go

We need to advertise the no-thin capability when the server does not support thin packs. This is important so that clients do not attempt to use thin packs when the server does not support them.

plumbing: transport, fix not advertising no-thin capability

---

plumbing/transport/receive_pack.go
plumbing/transport/receive_pack_test.go
plumbing/transport/serve.go
plumbing/transport/serve_test.go
plumbing/transport/upload_pack.go
plumbing/transport/upload_pack_test.go

This commit fixes the protocol version advertisement for the ReceivePack and UploadPack services. The version should be advertised during the advertisement phase if and only if we're advertising references during the ReceivePack or UploadPack routines.
This will also change the behavior of the AdvertiseReferences function to only accept UploadPackService and ReceivePackService as valid services.
It will also error out if the protocol version is not supported.

[v6] plumbing: transport, fix advertise protocol version

---

plumbing/transport/ssh/auth_method.go
plumbing/transport/ssh/auth_method_test.go
plumbing/transport/ssh/common.go
plumbing/transport/ssh/common_test.go

Re-adds support for cert authorities using skeema/knownhosts. 
It performs two separate changes: 
- Simplify the `AuthMethod`s provided by go-git so that they populate HostKeyCallback and HostKeyAlgorithms, while still allowing the user to inject a custom HostKeyCallback. If the HostKeyCallback is empty, then the `HostKeyCallback` and the `HostKeyAlgorithms` are set using the knownhosts DB functionality, which now supports cert authorities.
- Add an option so that a user of the default `AuthMethod`s provided by go-git can set a custom `HostKeyAlgorithms` when they use a custom `HostKeyCallback`. This is needed for usages of `ssh.FixedHostKey`.
fixes 1417

plumbing: add cert auth support to `releases/v5.x`

---

options.go
plumbing/protocol/packp/pushopts.go
plumbing/protocol/packp/pushopts_test.go
plumbing/protocol/packp/updreq.go
plumbing/protocol/packp/updreq_decode.go
plumbing/protocol/packp/updreq_decode_test.go
plumbing/protocol/packp/updreq_encode.go
plumbing/protocol/packp/updreq_encode_test.go
plumbing/transport/common.go
plumbing/transport/push.go
plumbing/transport/receive_pack.go
remote_test.go

This refactors the decoding of commands and capabilities in the update-requests decoder to avoid double decoding the commands and eating the next pktlines in the reader.
The issue was that the decoder doesn't stop once it reaches a flush packet and continues to read the next line. This is incorrect as an update-requests always expects a flush packet after the commands have been sent.

[v6] plumbing: fix, prevent double decoding of commands and flush

---

options.go
plumbing/transport/common.go
plumbing/transport/http/common.go
plumbing/transport/http/common_test.go
plumbing/transport/http/transport.go
remote.go
repository.go
worktree.go

This adds support for mTLS for the HTTPS protocol, the same way custom CA bundles were introduced for `v5`. It is specifically targeting `v5`, as I believe in `v6` we may benefit from a full rehaul of how we work with transports (and may benefit from more fine-grain `http.Transport` injection).

[v5] plumbing: support mTLS for HTTPS protocol

---

utils/merkletrie/change.go
utils/merkletrie/index/node.go
utils/merkletrie/index/node_test.go

Fix for https://github.com/go-git/go-git/issues/1455
When attempting to check out anything that isn't a root directory the Sparse Checkout options do not work correctly. This is reproducible with the examples in the above issue. 
"virtual" nodes are created in the tree that represent directories. The first time a file is added to the tree it's parts are split and any missing nodes (including any directories) are added to the tree. 
For example, if the first added file is `foo/bar/file.yaml` and this file should be skipped, entries are created for `foo`, `foo/bar`, and `foo/bar/file.yaml`, with all three entries setting `SkipWorktree` to `true`. If `foo/baz/file.yaml` is subsequently added, but should _not_ be skipped, this is the current bug. `foo` already exists in the tree, and had …

utils: fix diff so subpaths work for sparse checkouts, fixes 1455

---

plumbing/format/gitignore/pattern.go
plumbing/format/gitignore/pattern_test.go

e.g., the pattern `/a*/**` in `.gitignore` should not match a file `ab` in the project root.
Fix a broken test that was enforcing the incorrect behavior.
Fixes: Issue #154

plumbing: correct matching of file vs. dir globs in `.gitignore`, Fixes #154

---

plumbing/format/packfile/parser.go

this func could fail silently and couldn't be catch at higher level

plumbing: fix err mngt in packfile processDelta

---

blame.go
blame_test.go

remove unused result parameter and dead code

plumbing: blame simplification

---

plumbing/transport/receive_pack.go
plumbing/transport/receive_pack_test.go
plumbing/transport/upload_pack.go
plumbing/transport/upload_pack_test.go

Fixes a mistake made in #1488. Basis for the logic of this commit is [this implementation commit](https//github.com/git/git/commit/8f6982b4e16c60bba713a3b6592b2ff5c7476974#diff-8981f89ee862f086213310d567ec04fde00eb9fb3e23773aabb57be1dc46db53R55)

[v6] plumbing: transport, fix upload pack service for clients requesting version 2

---

backend/http/http.go
backend/http/http_test.go

This small change makes the backend more idiomatic by removing `BackendOptions` and making `Backend` implement the [http.Handler] interface directly. The loader is now part of the `Backend` struct.

[v6] backend: http, make backend more idiomatic

---

config/config.go
config/config_test.go
go.mod
go.sum
plumbing/format/config/decoder_test.go

step 1 in fix for issue #1197
point go.mod to fork of gcfg that removes empty subsection name check and error
This will stop go-git from throwing an error when parsing a config file with an empty subsection name.
To match git we'll have to account for options that fall under empty subsection names like URLs for example during config marshal/unmarshal.

plumbing: format/config, remove empty config subsection name test

---

.github/workflows/cifuzz.yml
plumbing/transport/transport_test.go

The `oss-fuzz` project seem to have a limitation when the Go built-in Fuzz is being used, to workaround the issue the fuzzing test package is being renamed.

Fix fuzzing tests

---

backend/git/git.go
plumbing/transport/loader.go
plumbing/transport/transport.go

This implements a Git transport backend ~and server~ for Go-Git. ~The backend expects a `net.Conn` and handles raw Git transport protocol requests. It is suitable to be used with a `net.Listener` or any other `net.Conn` source.~ The server implementation has been moved to go-git/cli https://github.com/go-git/cli/pull/13.
~Since Go doesn't have a standard raw TCP server API, we need a new `git.Server` to handle our requests. The API looks as follows.~
I'm still not sure if we should keep a TCP server implementation in `go-git`. Perhaps that code can live somewhere else where we don't need to maintain it here, like in `go-git/cli`. Please see https://github.com/go-git/cli/pull/13
```go
// Backend represents a Git transport server handler that can handle git-upload-pack, git-receive-pack, …
```

[v6] backend: add git transport backend

---

plumbing/transport/build_update_requests_test.go
plumbing/transport/push.go
plumbing/transport/serve.go

The gitprotocol-pack documentation of send-pack capabilities is outdated or not up-to-date, and the upstream Git source code shows otherwise.
This commits updates the send-pack capabilities to match what upstream Git supports and adds support to side-band and quiet capabilities.
Fixes: https://github.com/go-git/go-git/issues/1571

plumbing: transport, fix send-pack capabilities

---

plumbing/transport/pack.go
plumbing/transport/pack_test.go

when err is `EOF`, the ssh connection not closed
```
$ lsof -p 4883 | grep ":ssh" | awk -F '->' '{print $2}' | sort | uniq -c
21 127.0.1.100:ssh (ESTABLISHED)
151 127.0.1.101:ssh (ESTABLISHED)
```

plumbing: transport, fix ssh connection leak when start return err EOF

---

plumbing/format/gitignore/matcher_test.go

Test that the "exclude everything except" example
from https://git-scm.com/docs/gitignore works (it does).
I wrote this test to understand how the "!" handling works.
It may be useful to others, so there's the PR instead of throwing it away.

plumbing: gitignore, add EverythingExceptExample test

---

plumbing/transport/ssh/upload_pack_test.go
remote_test.go
repository_test.go
utils/merkletrie/filesystem/node_test.go
worktree_test.go

Some of the tests need new directories created, some of them are not deleting those long-lasting dirs, resulting in leftover temporary directories after the test execution. This PR leans on the use of dir creation for tests, which are automatically removed after the test execution.

*: Use ephemeral dir creation for tests

---

plumbing/object/commit.go
plumbing/object/commit_test.go

This adds support for extra headers. While git has a set of  ["standard headers"] (`tree`, `parent`, `author`, `committer`, and `encoding`), it will also support [extra headers] when serializing.
The extra headers must come after the standard ones, but they are otherwise freetyped.
[Jujutsu] takes advantage of that to store its own identifier (`change-id`) as an extra header.
Because signatures will cover the hash of the whole commit (standard headers, extra headers and the message. Everything but the signature itself), if we deserialize a commit and then `EncodeWithoutSignature` to get back the "canonical" representation of a commit, if we don't serialize back the extra headers, the hash will no longer match and the signature will fail to verify.
This adds support for parsing and …

plumbing: support commits extra headers, support jujutsu signed commit [5.x]
