go-git/go-git

plumbing/protocol/packp/advrefs.go
plumbing/protocol/packp/advrefs_test.go
plumbing/transport/internal/common/common.go

plumbing: transport, fix handling of empty adv-refs on upload-pack

---

README.md

Change storer:
- from godoc.org
- to pkg.go.dev

Change the link of the storer docs

---

.github/workflows/git.yml

ci: fix CI, git compaitiblity

---

plumbing/object/rename.go

Discovered while building on a Raspberry Pi

fix 32 bit build

---

plumbing/object/patch.go

I don't understand the usage of the word text here. It looks like a mistake.

Remove unnecessary text from comment

---

plumbing/object/commit.go
plumbing/object/commit_test.go
plumbing/object/tree_test.go

plumbing: object, Commit.Patch support to as nil

---

_examples/README.md
_examples/submodule/main.go

Hi !
Thanks for this project 👍 
The goal of this pull request is to add an example of how to make
the equivalent of `git submodule update --remote` with `go-git`

_examples: submodule, adding an example with submodule update

---

config/config_test.go
options.go
options_test.go
repository_test.go

All the test suite for config was improved.

CreateTagOptions.Validate: load Tagger from config

---

plumbing/memory.go
plumbing/memory_test.go

Replace the bytes.Buffer with a bytes.Reader wrapped in a custom NopCloser, so that the extra reading methods are sill accessible.

plumbing: memoryobject, make blob reader seekable

---

_examples/README.md
_examples/clone/auth/ssh/main.go

chore: add an exmaple: clone with ssh

---

repository.go
repository_test.go

PlainOpenWithOptions: support file path

---

plumbing/storer/object.go

This project has such helpful docs. I wanted to take a moment to contribute a little.

Improve grammar in plumbing/storer/object Go Doc

---

options.go

Small typo fix `compatility` -> `compatibility`

*: fix typographical error

---

.github/workflows/test.yml

test should be running with the latest two go versions

.github: update go version

---

go.mod
go.sum

Description
See https://github.com/xanzy/ssh-agent/pull/11
Fixes https://github.com/go-git/go-git/issues/616

plumbing: transport/ssh: fix panic on Windows 10 with paegent as ssh-agent

---

common_test.go
repository_test.go
submodule_test.go

Also cleaned up a few Code Analysis warnings

git: Testing, Fix tests not cleaning temp folders

---

repository.go
repository_test.go

git: Clone HEAD should not force master. Fixes #363

---

.github/workflows/git.yml

*: Fix broken CI

---

worktree.go

git: worktree, apply ProxyOption on Pull

---

plumbing/object/commit.go
plumbing/object/commit_test.go

When a merge commit is created from merging a signed tag, the tag object is embedded in the commit object. This commit adds support for this tag data when encoding and decoding a commit object.
It might be possible to embed the Tag struct in the Commit struct. However, that will also require additions to the tag object to use reader / writer, like the Signature object currently does.
NOTE: I haven't included any tests as I'm currently unfamiliar with the test workflow used in this repo. Some pointers would be appreciated!

plumbing/object: Support mergetag in merge commits

---

.github/workflows/stale-issues-bot.yaml

Improve the format of the message and ensure that the bot is handling issues in ascending order.

*: Change stale bot order to ascending and improve msg format

---

.github/workflows/cifuzz.yml
Makefile
oss-fuzz.sh
utils/merkletrie/internal/fsnoder/new_test.go

Add [cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) and [seed-corpus](https://go.dev/security/fuzz/#glos-seed-corpus) 
Note: Don't merge this now, after https://github.com/google/oss-fuzz/pull/11069

[fuzzing] add cifuzz and update fuzzers

---

plumbing/format/packfile/diff_delta.go
plumbing/format/packfile/patch_delta.go

The changes aim to simplify the code and reduce duplication.
Follow-up from https://github.com/go-git/go-git/pull/799/files#r1383091570.

plumbing: format/packfile, Refactor patch delta

---

go.mod
go.sum
plumbing/transport/file/client.go
plumbing/transport/server/server.go
remote.go
utils/ioutil/common.go
utils/ioutil/pipe.go
utils/ioutil/pipe_js.go

ioutil.Pipe literally calls io.Pipe

utils: remove ioutil.Pipe and use std library io.Pipe

---

plumbing/transport/git/common_test.go

When running the tests in an install in which git daemon is not installed (e.g. openSUSE), all the git transport tests will fail with a connection refused error. This was due the git server not being running in the first place. The tests will now fail with `git daemon cannot be found`.

plumbing: transport/git, Improve tests error message

---

plumbing/transport/ssh/common.go
plumbing/transport/ssh/common_test.go

plumbing: check setAuth error. Fixes #185

---

plumbing/object/commit.go
plumbing/object/commit_test.go

update var defaultUtf8CommitMessageEncoding  name

object: fix variable  defaultUtf8CommitMessageEncoding name spell error

---

go.mod
go.sum

build: Bump github.com/sergi/go-diff

---

worktree_commit.go
worktree_commit_test.go

Made (*Worktree).Commit to apply worktree changes when opt.Amend flag is set to true.
If amend flag is set to true, it sets new commit's parent as head's parent so it can replace head.  
it also deletes original head commit object when everything goes well.
Fixes #1024

git: worktree_commit, Fix amend commit to apply changes. Fixes #1024

---

options.go
options_test.go

git: Add commit validation for Reset

---

.github/workflows/stale-issues-bot.yaml
plumbing/format/index/decoder.go
repository.go
storage/filesystem/dotgit/dotgit_test.go
worktree_linux.go
worktree_status.go

Fixes some lint warnings and increases the stalebot stale check to 180 days.

Fix some lint warning and increase stalebot to 180 days

---

_examples/README.md
_examples/common_test.go
_examples/config/main.go
_examples/performance/clone/main.go
config/config_test.go
plumbing/format/index/encoder.go
plumbing/format/index/encoder_test.go
storage/filesystem/dotgit/dotgit_test.go
utils/merkletrie/difftree.go
utils/sync/bufio.go
utils/sync/bytes.go
utils/sync/zlib.go
worktree.go
worktree_test.go

- 39d6d712: [_examples: Add performance focused clone example](https://github.com/go-git/go-git/commit/7d6d210bad3af5dd53756dec327ee50d0d5f3ac3)
- #1251
- #1148
- #557
- #1177
- #1182

[v6-exp] New performance focused clone example + forward ports

---

.github/workflows/cifuzz.yml
.github/workflows/codeql.yml
.github/workflows/git.yml
.github/workflows/pr-validation.yml
.github/workflows/stale-issues-bot.yaml
.github/workflows/test.yml
blame.go
go.mod
plumbing/reference.go
plumbing/reference_test.go

- build: Fix `go-git-fixtures/v5` version
- build: Align workflow permissions
- #1257
- #1182

[v6-exp] Build improvements + forward ports

---

plumbing/format/pktline/length.go
plumbing/format/pktline/scanner_test.go

Pull request which is the same as #1220 but for v6-exp branch.

pktline : Accept uppercase hexa in pktline length

---

worktree_commit.go
worktree_commit_test.go

Pull request which is the same as #1261 but for v6-exp branch.

git: worktree_commit, sanitize author and commiter name and email before creating the commit object. Fixes #680

---

plumbing/object/blob_test.go
plumbing/object/change_adaptor_test.go
plumbing/object/change_test.go
plumbing/object/commit_stats_test.go
plumbing/object/commit_test.go
plumbing/object/commit_walker_bfs_filtered_test.go
plumbing/object/commit_walker_test.go
plumbing/object/commitgraph/commitnode_test.go
plumbing/object/difftree_test.go
plumbing/object/file_test.go
plumbing/object/merge_base_test.go
plumbing/object/object_test.go
plumbing/object/patch_stats_test.go
plumbing/object/patch_test.go
plumbing/object/rename_test.go
plumbing/object/tag_test.go
plumbing/object/tree_test.go

plumbing: object, gocheck to testify migration. Fixes #1297

---

internal/revision/parser_test.go
internal/revision/scanner_test.go
internal/transport/http/proxy_test.go
internal/transport/http/test/test_utils.go
internal/transport/ssh/test/proxy_test.go
internal/transport/test/receive_pack.go
internal/transport/test/upload_pack.go
internal/url/url_test.go
plumbing/server/receive_pack_test.go
plumbing/server/server_test.go
plumbing/server/upload_pack_test.go
plumbing/transport/common_test.go
plumbing/transport/file/client_test.go
plumbing/transport/file/common_test.go
plumbing/transport/file/receive_pack_test.go
plumbing/transport/file/server_test.go
plumbing/transport/file/upload_pack_test.go
plumbing/transport/git/common_test.go
plumbing/transport/git/receive_pack_test.go
plumbing/transport/git/upload_pack_test.go
plumbing/transport/http/common_test.go
plumbing/transport/http/proxy_test.go
plumbing/transport/http/receive_pack_test.go
plumbing/transport/http/upload_pack_test.go
plumbing/transport/registry_test.go
plumbing/transport/ssh/auth_method_test.go
plumbing/transport/ssh/common_test.go
plumbing/transport/ssh/proxy_test.go
plumbing/transport/ssh/upload_pack_test.go
plumbing/transport/transport_test.go

~Based on https://github.com/go-git/go-git/pull/1275~
Supersedes: https://github.com/go-git/go-git/pull/1275

plumbing: transport, go check to testify migration

---

plumbing/transport/common.go
plumbing/transport/file/client.go
plumbing/transport/http/common.go
plumbing/transport/negotiate.go
plumbing/transport/pack.go
plumbing/transport/upload_pack.go
remote.go
submodule.go

This uses goroutines instead of sequential flow when handling pack negotiation and upload.

[v6]: Fix misc transport issues

---

remote.go
remote_test.go

Fixes two of the failing tests in the `v6-transport` branch.

Fix tests TestGetHaves and TestPushContext

---

.github/workflows/git.yml
.github/workflows/test.yml
plumbing/protocol/packp/capability/capability.go

Follow-up from #1409. The Windows tests will be fixed in a separate PR.

Update user-agent to `go-git/6.x`

---

plumbing/format/objfile/writer.go

We observed unexpected behavior where `objfile.Close()` is called multiple times. This is likely caused by `sync.PutZlibWriter(w.zlib)`, which can lead to race conditions and unintended side effects during fast parallel writes.
This pull request ensures that calling `Close()` multiple times is idempotent, aligning with common patterns in other `io.Writer` implementations. After the first call, subsequent calls will have no effect and return the same error, if any.
Reproduce with fast concurrent writes and the following sample code:
```golang
func Encode(objectType plumbing.ObjectType, data []byte) (plumbing.Hash, []byte, error) {
var buffer bytes.Buffer
writer := objfile.NewWriter(&buffer)
defer writer.Close()
if err := writer.WriteHeader(objectType, int64(len(data))); err != nil {
return …
```

plumbing: make objfile closing idempotent

---

plumbing/transport/ssh/auth_method.go
plumbing/transport/ssh/auth_method_test.go

The PR #1482 renamed `SetHostKeyCallback` to `SetHostKeyCallbackAndAlgorithms`, due to the change in behaviour in that method. For keeping backwards compatibility with v5, a new `SetHostKeyCallback` is being introduced that simply calls back to `SetHostKeyCallbackAndAlgorithms`.
Some tests were introduced to enforce expected behaviour.

plumbing: transport, Reintroduce SetHostKeyCallback. Fix #1514
